package linea.config.docs

/**
 * Generates the human-readable Markdown reference for a config.
 *
 * Output mirrors the JSON snapshot's per-file organisation (see [ConfigFileRoot]): one `##`
 * heading per config file, a `###` heading per top-level section within it, and a table of that
 * section's leaf keys (deep, with full dotted paths). Deprecated keys are also collected into a
 * trailing "Deprecated Keys" table. The file is committed and regenerated by CI; it is not meant
 * to be edited by hand.
 *
 * @param title the top-level document title.
 * @param regenerateCommand the command shown in the "do not edit" banner.
 */
object ConfigDocMarkdownGenerator {
  fun generate(
    files: List<ConfigFileRoot>,
    sectionDetector: SectionDetector,
    title: String,
    regenerateCommand: String,
  ): String {
    val sb = StringBuilder()
    sb.appendLine("# $title")
    sb.appendLine()
    sb.appendLine("<!-- Generated by $regenerateCommand. Do not edit by hand. -->")
    sb.appendLine()

    val deprecated = mutableListOf<Pair<String, ConfigKey>>() // file label -> key

    for (file in files) {
      val keys = ConfigSchemaWalker.walk(file.rootClass, sectionDetector)
      keys.filter { it.deprecated }.forEach { deprecated.add(file.label to it) }

      sb.appendLine("## ${file.label}")
      sb.appendLine()
      sb.appendLine(file.description)
      sb.appendLine()

      val topLevelLeaves = keys.filter { !it.path.contains(".") && !it.isSection }
      if (topLevelLeaves.isNotEmpty()) {
        appendTable(sb, topLevelLeaves)
        sb.appendLine()
      }

      val topLevelSections = keys.filter { !it.path.contains(".") && it.isSection }
      for (section in topLevelSections) {
        sb.appendLine("### `${section.path}`")
        sb.appendLine()
        if (section.description.isNotBlank()) {
          sb.appendLine(section.description)
          sb.appendLine()
        }
        val leaves = keys.filter { it.path.startsWith("${section.path}.") && !it.isSection }
        appendTable(sb, leaves)
        sb.appendLine()
      }
    }

    sb.appendLine("## Deprecated Keys")
    sb.appendLine()
    if (deprecated.isEmpty()) {
      sb.appendLine("None.")
    } else {
      sb.appendLine("| File | Key | Replacement | Description |")
      sb.appendLine("| --- | --- | --- | --- |")
      for ((label, key) in deprecated) {
        sb.appendLine(
          "| ${cell(label)} | `${key.path}` | ${key.replacement?.let { "`$it`" } ?: "-"} " +
            "| ${cell(key.description)} |",
        )
      }
    }
    sb.appendLine()
    return sb.toString()
  }

  private fun appendTable(sb: StringBuilder, leaves: List<ConfigKey>) {
    sb.appendLine("| Key | Type | Required | Default | Status | Description |")
    sb.appendLine("| --- | --- | --- | --- | --- | --- |")
    for (key in leaves) {
      sb.appendLine(
        "| `${key.path}` | `${key.type}` | ${if (key.required) "yes" else "no"} " +
          "| ${key.default?.let { "`$it`" } ?: "-"} | ${if (key.deprecated) "deprecated" else "active"} " +
          "| ${describe(key)} |",
      )
    }
  }

  private fun describe(key: ConfigKey): String {
    val example = key.example?.let { " Example: `$it`." } ?: ""
    return cell(key.description + example)
  }

  /** Escapes Markdown table cell content (pipes would otherwise break the row). */
  private fun cell(text: String): String = text.replace("|", "\\|")
}
