package linea.config.docs

/**
 * Generates an MDX-safe reference partial for a config.
 *
 * The output mirrors [ConfigDocMarkdownGenerator] but drops the top-level `# title` heading and
 * the "do not edit" banner (the human-owned wrapper page supplies the title and provenance), and
 * escapes content so it can be imported as an MDX component. MDX is stricter than Markdown:
 * - `{` and `}` start JSX expression containers, so they are backslash-escaped.
 * - `<` and `>` would start JSX tags, so they are HTML-entity escaped.
 * - backticks inside inline code are emitted as `&#96;` to avoid breaking the code span.
 * - `|` in table cells is backslash-escaped (same as Markdown).
 *
 * The partial is intended to be written to a gitignored build directory and published by CI to
 * `docs/stack/reference/_generated/<component>/reference.mdx` on the docs site; it is not meant
 * to be edited by hand or committed to the application repository.
 *
 * @param regenerateCommand the command shown in the MDX comment banner.
 */
object ConfigDocMdxGenerator {
  fun generate(
    files: List<ConfigFileRoot>,
    sectionDetector: SectionDetector,
    regenerateCommand: String,
  ): String {
    val sb = StringBuilder()
    sb.appendLine("{/* Generated by $regenerateCommand. Do not edit by hand. */}")
    sb.appendLine()

    val deprecated = mutableListOf<Pair<String, ConfigKey>>() // file label -> key

    for (file in files) {
      val keys = ConfigSchemaWalker.walk(file.rootClass, sectionDetector)
      keys.filter { it.deprecated }.forEach { deprecated.add(file.label to it) }

      sb.appendLine("## ${escapeText(file.label)}")
      sb.appendLine()
      sb.appendLine(escapeText(file.description))
      sb.appendLine()

      val topLevelLeaves = keys.filter { !it.path.contains(".") && !it.isSection }
      if (topLevelLeaves.isNotEmpty()) {
        appendTable(sb, topLevelLeaves)
        sb.appendLine()
      }

      val topLevelSections = keys.filter { !it.path.contains(".") && it.isSection }
      for (section in topLevelSections) {
        sb.appendLine("### `${escapeInlineCode(section.path)}`")
        sb.appendLine()
        if (section.description.isNotBlank()) {
          sb.appendLine(escapeText(section.description))
          sb.appendLine()
        }
        val leaves = keys.filter { it.path.startsWith("${section.path}.") && !it.isSection }
        appendTable(sb, leaves)
        sb.appendLine()
      }
    }

    sb.appendLine("## Deprecated Keys")
    sb.appendLine()
    if (deprecated.isEmpty()) {
      sb.appendLine("None.")
    } else {
      sb.appendLine("| File | Key | Replacement | Description |")
      sb.appendLine("| --- | --- | --- | --- |")
      for ((label, key) in deprecated) {
        sb.appendLine(
          "| ${escapeText(label)} | `${escapeInlineCode(key.path)}` " +
            "| ${key.replacement?.let { "`" + escapeInlineCode(it) + "`" } ?: "-"} " +
            "| ${escapeText(key.description)} |",
        )
      }
    }
    sb.appendLine()
    return sb.toString()
  }

  private fun appendTable(sb: StringBuilder, leaves: List<ConfigKey>) {
    sb.appendLine("| Key | Type | Required | Default | Status | Description |")
    sb.appendLine("| --- | --- | --- | --- | --- | --- |")
    for (key in leaves) {
      sb.appendLine(
        "| `${escapeInlineCode(key.path)}` | `${escapeInlineCode(key.type)}` " +
          "| ${if (key.required) "yes" else "no"} " +
          "| ${key.default?.let { "`" + escapeInlineCode(it) + "`" } ?: "-"} " +
          "| ${if (key.deprecated) "deprecated" else "active"} " +
          "| ${describe(key)} |",
      )
    }
  }

  private fun describe(key: ConfigKey): String {
    val example = key.example?.let { " Example: `" + escapeInlineCode(it) + "`." } ?: ""
    return escapeText(key.description + example)
  }

  /**
   * Escapes free-running prose text for MDX. Collapses newlines to spaces (tables are single-line),
   * escapes braces (JSX expression containers), angle brackets (JSX tags), and pipes (table
   * delimiters). Backticks are left alone because prose is not inside an inline code span.
   */
  private fun escapeText(text: String): String =
    text.replace("\r\n", " ").replace("\n", " ").replace("\r", " ")
      .replace("{", "\\{").replace("}", "\\}")
      .replace("<", "&lt;").replace(">", "&gt;")
      .replace("|", "\\|")

  /**
   * Escapes text rendered inside backtick inline code. Backticks would close the span, so they are
   * emitted as `&#96;`; braces and pipes are escaped the same way as [escapeText]. Angle brackets
   * are entity-escaped so the code span stays MDX-safe.
   */
  private fun escapeInlineCode(text: String): String =
    text.replace("\r\n", " ").replace("\n", " ").replace("\r", " ")
      .replace("\\", "\\\\")
      .replace("`", "&#96;")
      .replace("{", "\\{").replace("}", "\\}")
      .replace("<", "&lt;").replace(">", "&gt;")
      .replace("|", "\\|")
}
