package codegen

import (
	"fmt"
	"io"
	"strings"
	"text/template"

	"github.com/LFDT-Lineth/lineth-monorepo/prover-ray/maths/koalabear/field"
)

// PcsZigOptions configures imports and the constant naming for generated
// `pcs.System` data.
type PcsZigOptions struct {
	// PcsImport is the Zig module exposing `System` / `ColumnDesc` / `ClaimRef`
	// / `BatchRoot`. FriImport exposes `Params`. When empty, verifier-ray-relative
	// defaults are used.
	PcsImport string
	FriImport string
	// FieldImport is kept for parity with the other emitters' option structs and
	// the existing generator call sites. PCS roots are emitted inline, so the
	// current template does not need this import directly.
	FieldImport string
	// ConstName is the emitted `System` const name. Empty -> `pcs_system_<index>`.
	ConstName string
	// ConstPrefix namespaces the supporting consts (maps, roots) so several PCS
	// systems can coexist in one file. Empty -> no prefix.
	ConstPrefix string
	// EmitHeader, when true, prepends the import declarations.
	EmitHeader bool
}

func defaultPcsZigOptions() PcsZigOptions {
	return PcsZigOptions{
		PcsImport:   `@import("../query/pcs.zig")`,
		FriImport:   `@import("../query/fri.zig")`,
		FieldImport: `@import("../field/koalabear.zig")`,
		EmitHeader:  true,
	}
}

// WritePcsSystemZig writes the Zig source for one PcsSystem as a literal
// `pcs.System`.
func WritePcsSystemZig(w io.Writer, index int, system PcsSystem) error {
	return WritePcsSystemZigWithOptions(w, index, system, defaultPcsZigOptions())
}

func WritePcsSystemZigWithOptions(w io.Writer, index int, system PcsSystem, opts PcsZigOptions) error {
	data := newPcsTemplateData(index, system, opts)
	tmpl, err := template.New("pcs").Funcs(template.FuncMap{
		"octuplet": pcsOctupletLiteral,
		"shifts":   intArray,
	}).Parse(pcsZigTemplate)
	if err != nil {
		return err
	}
	return tmpl.Execute(w, data)
}

type pcsTemplateData struct {
	Options      PcsZigOptions
	Index        int
	System       PcsSystem
	ConstName    string
	Prefix       string
	WitnessName  string
	QuotientName string
	RootsName    string
}

func newPcsTemplateData(index int, system PcsSystem, opts PcsZigOptions) pcsTemplateData {
	def := defaultPcsZigOptions()
	if opts.PcsImport == "" {
		opts.PcsImport = def.PcsImport
	}
	if opts.FriImport == "" {
		opts.FriImport = def.FriImport
	}
	if opts.FieldImport == "" {
		opts.FieldImport = def.FieldImport
	}
	if opts.ConstName == "" {
		opts.ConstName = fmt.Sprintf("pcs_system_%d", index)
	}
	return pcsTemplateData{
		Options:      opts,
		Index:        index,
		System:       system,
		ConstName:    opts.ConstPrefix + opts.ConstName,
		Prefix:       opts.ConstPrefix,
		WitnessName:  opts.ConstPrefix + "witness_map",
		QuotientName: opts.ConstPrefix + "quotient_map",
		RootsName:    opts.ConstPrefix + "batch_roots",
	}
}

const pcsZigTemplate = `{{if .Options.EmitHeader}}// Code generated by verifier-ray/testdata/generate; DO NOT EDIT.

const pcs = {{.Options.PcsImport}};
const fri = {{.Options.FriImport}};

{{end}}const {{.WitnessName}} = [_]pcs.ClaimRef{
{{range .System.WitnessMap}}    .{ .col_decl_idx = {{.ColDeclIdx}}, .shift = {{.Shift}} },
{{end}}};
const {{.QuotientName}} = [_]pcs.ClaimRef{
{{range .System.QuotientMap}}    .{ .col_decl_idx = {{.ColDeclIdx}}, .shift = {{.Shift}} },
{{end}}};
const {{.RootsName}} = [_]pcs.BatchRoot{
{{range .System.BatchRoots}}{{if .Precomputed}}    .{ .precomputed = {{octuplet .Root}} },
{{else}}    .{ .round = {{.RoundIndex}} },
{{end}}{{end}}};

pub const {{.ConstName}} = pcs.System{
    .envelope_params = fri.Params{ .log_codeword_size = {{.System.LogCodewordSize}}, .log_plaintext_size = {{.System.LogPlaintextSize}}, .log_final_poly_size = {{.System.LogFinalPolySize}}, .num_queries = {{.System.NumQueries}} },
    .columns = &.{
{{range .System.Columns}}        .{ .batch_idx = {{.BatchIdx}}, .is_ext = {{.IsExt}}, .size = {{if .IsDynamic}}.{ .dynamic = .{ .index = {{.DynamicIndex}}, .min_size_log2 = {{.DynamicMinSizeLog2}} } }{{else}}.{ .static = {{.SizeLog2}} }{{end}}, .shifts = &[_]isize{{shifts .Shifts}} },
{{end}}    },
    .num_batches = {{.System.NumBatches}},
    .max_entries = {{.System.MaxEntries}},
    .max_size_log2 = {{.System.MaxSizeLog2}},
    .witness_map = &{{.WitnessName}},
    .quotient_map = &{{.QuotientName}},
    .batch_roots = &{{.RootsName}},
    .zeta_coin_index = {{.System.ZetaCoinIndex}},
};
`

// pcsOctupletLiteral emits a precomputed-batch root as an `[8]field.Element`
// literal `.{ .{ .value = v0 }, ... }`.
func pcsOctupletLiteral(o field.Octuplet) string {
	parts := make([]string, len(o))
	for i := range o {
		parts[i] = fmt.Sprintf(".{ .value = %d }", o[i].Uint64())
	}
	return ".{ " + strings.Join(parts, ", ") + " }"
}
