package codegen

import (
	"fmt"
	"io"
	"strings"
	"text/template"
)

// PublicInputZigOptions configures generated protocol.public_input.Spec data.
type PublicInputZigOptions struct {
	ProtocolImport string
	ConstName      string
	EmitHeader     bool
}

func defaultPublicInputZigOptions() PublicInputZigOptions {
	return PublicInputZigOptions{
		ProtocolImport: `@import("../protocol/root.zig")`,
		ConstName:      "public_input",
		EmitHeader:     true,
	}
}

// WritePublicInputSystemZig writes generated Zig source containing the
// protocol.public_input.Spec value for the supplied public-input layout.
func WritePublicInputSystemZig(w io.Writer, system PublicInputSystem) error {
	return WritePublicInputSystemZigWithOptions(w, system, defaultPublicInputZigOptions())
}

func WritePublicInputSystemZigWithOptions(w io.Writer, system PublicInputSystem, opts PublicInputZigOptions) error {
	tmpl, err := template.New("public_input").Funcs(template.FuncMap{
		"intArray": intArray,
		"refs":     publicInputRefs,
	}).Parse(publicInputZigTemplate)
	if err != nil {
		return err
	}
	return tmpl.Execute(w, publicInputZigData{Options: opts, System: system})
}

type publicInputZigData struct {
	Options PublicInputZigOptions
	System  PublicInputSystem
}

const publicInputZigTemplate = `{{if .Options.EmitHeader}}// Code generated by verifier-ray/testdata/generate; DO NOT EDIT.

const protocol = {{.Options.ProtocolImport}};

{{end}}pub const {{.Options.ConstName}} = protocol.public_input.Spec{
    .round_cell_counts = &[_]usize{{intArray .System.RoundCellCounts}},
    .refs = &[_]protocol.public_input.CellRef{{refs .System.Refs}},
};
`

func publicInputRefs(refs []PublicInputRef) string {
	if len(refs) == 0 {
		return "{}"
	}

	var out strings.Builder
	out.WriteString("{ ")
	for i, ref := range refs {
		if i > 0 {
			out.WriteString(", ")
		}
		fmt.Fprintf(
			&out,
			".{ .statement_index = %d, .round = %d, .index = %d }",
			ref.StatementIndex,
			ref.Round,
			ref.Index,
		)
	}
	out.WriteString(" }")
	return out.String()
}
