plugins {
  id 'lineth.kotlin-library-minimal-conventions'
  id 'java-library'
}

dependencies {
  api project(":linea-besu:besu")

  api("io.consensys.tuweni:tuweni-bytes:${libs.versions.tuweni.get()}") {
    transitive = false
  }

  api("io.consensys.tuweni:tuweni-units:${libs.versions.tuweni.get()}") {
    transitive = false
  }

  implementation("org.bouncycastle:bcpkix-jdk18on:${libs.versions.bouncycastle.get()}") {
    because "necessary for besu Transaction object that verifies signatures"
  }
  implementation("org.bouncycastle:bcprov-jdk18on:${libs.versions.bouncycastle.get()}") {
    because "necessary for besu Transaction object that verifies signatures"
  }
  implementation("com.github.ben-manes.caffeine:caffeine:${libs.versions.caffeine.get()}") {
    because "besu's Address static initializer caches with Caffeine as of besu 26.6.1"
  }
}
