plugins {
  id 'net.consensys.zkevm.kotlin-library-conventions'
}

dependencies {
  api "com.fasterxml.jackson.core:jackson-annotations"
  api "com.fasterxml.jackson.core:jackson-databind"
  api "com.fasterxml.jackson.module:jackson-module-kotlin"
  api("com.fasterxml.jackson.datatype:jackson-datatype-jsr310")
  api(project(":jvm-libs:generic:extensions:kotlin"))
  api(project(":coordinator:core-interfaces"))
}
