#!/usr/bin/env bash
# Validates that the generated MDX partial is safe to import into Docusaurus.
#
# Checks:
#   1. The file exists and is non-empty.
#   2. The first line is the generated-content banner.
#   3. After the banner, every '{' is backslash-escaped and every '<'/'>' is
#      HTML-entity escaped, so the partial can be imported as MDX.
#
# Env:
#   MDX_PARTIAL_PATH  repo-relative path to the generated MDX partial
set -euo pipefail

MDX="${MDX_PARTIAL_PATH:-}"
if [[ -z "$MDX" ]]; then
  echo "::error::MDX_PARTIAL_PATH is empty" >&2
  exit 1
fi

if [[ ! -s "$MDX" ]]; then
  echo "::error::Expected non-empty MDX partial at $MDX"
  exit 1
fi

# Banner: {/* Generated by <task>. Do not edit by hand. */}
# In ERE, \* matches a literal asterisk (single backslash, not double).
if ! head -n 1 "$MDX" | grep -qE '^\{/\* Generated by .*\. Do not edit by hand\. \*/}$'; then
  echo "::error::MDX partial at $MDX is missing the generated-content banner"
  exit 1
fi

# After the banner, every '{' must be backslash-escaped.
body="$(tail -n +2 "$MDX")"
if printf '%s' "$body" | grep -nP '(?<!\\)\{' >/dev/null; then
  echo "::error::MDX partial contains an unescaped '{' that would break MDX imports"
  exit 1
fi

# Every '<' or '>' must be HTML-entity escaped. Use lookbehind so a leading '>'
# at the start of a line is still caught (the previous [^&] alternative missed it).
if printf '%s' "$body" | grep -nP '<(?!;)|(?<!&)>(?!;)' >/dev/null; then
  echo "::error::MDX partial contains a raw '<' or '>' that would break MDX imports"
  exit 1
fi

echo "MDX partial OK ($MDX, $(wc -c < "$MDX") bytes)"
