plugins {
  id 'lineth.kotlin-common-conventions'
  id 'java-test-fixtures'
}

description="Lineth domain models"

dependencies {
  implementation project(":jvm-libs:generic:extensions:kotlin")
  testFixturesApi project(":jvm-libs:linea:besu-libs")
  testFixturesApi project(":jvm-libs:generic:extensions:kotlin")
}

jar {
  dependsOn configurations.runtimeClasspath
}
