// Package main generates Zig golden-test vectors from prover-ray.
//
// The generator is intentionally written in Go because prover-ray is the source
// of truth for protocol behavior. Each writer below computes expected values
// with prover-ray packages, serializes those values as Zig literals, and writes
// them to testdata/generated/vectors.zig. The Zig tests then replay the same
// operations in verifier-ray and compare against these generated vectors.
package main

import (
	"bytes"
	"fmt"
	"math/rand/v2"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	fiatshamir "github.com/LFDT-Lineth/lineth-monorepo/prover-ray/crypto/koalabear/fiatshamir"
	"github.com/LFDT-Lineth/lineth-monorepo/prover-ray/crypto/koalabear/fri"
	poseidon2 "github.com/LFDT-Lineth/lineth-monorepo/prover-ray/crypto/koalabear/poseidon2"
	"github.com/LFDT-Lineth/lineth-monorepo/prover-ray/maths/koalabear/field"
	"github.com/LFDT-Lineth/lineth-monorepo/prover-ray/maths/koalabear/polynomials"
	"github.com/LFDT-Lineth/lineth-monorepo/prover-ray/wiop"
	"github.com/LFDT-Lineth/lineth-monorepo/prover-ray/wiop/compilers/global"
	"github.com/LFDT-Lineth/lineth-monorepo/prover-ray/wiop/compilers/localvanishing"
	"github.com/LFDT-Lineth/lineth-monorepo/prover-ray/wiop/compilers/logderivativesum"
	"github.com/LFDT-Lineth/lineth-monorepo/prover-ray/wiop/compilers/lookuptologderivsum"
	pcscompiler "github.com/LFDT-Lineth/lineth-monorepo/prover-ray/wiop/compilers/pcs"
	"github.com/LFDT-Lineth/lineth-monorepo/prover-ray/wiop/compilers/rangecheck"
	"github.com/LFDT-Lineth/lineth-monorepo/prover-ray/wiop/wioptest"
	"github.com/consensys/linea-monorepo/verifier-ray/codegen"
)

const koalaModulus = uint64(2_130_706_433)

func main() {
	// Shrink the FRI query count to 1 for fixtures: the production default (229)
	// would emit ~229 Merkle branches per opening, ballooning verify.zig to
	// hundreds of MB and making Zig compilation intractable. One query exercises
	// the same code paths byte-faithfully (the verifier derives the query count
	// from the emitted System params, which reflect this override).
	pcscompiler.SetFRINumQueriesForTest(1)

	var out bytes.Buffer
	writeHeader(&out)
	writeFieldCases(&out)
	writeExtCases(&out)
	writePolynomialCases(&out)
	writePoseidonCases(&out)
	writeFiatShamirCases(&out)
	writeRuntimeTraceCases(&out)
	fixtureCases, compiledSystems, err := buildCompiledFixtureCases()
	if err != nil {
		panic(err)
	}

	data := out.Bytes()
	zigfmt, err := runZigFmt(data)
	if err == nil {
		data = zigfmt
	}

	outputPath := filepath.Join("..", "generated", "vectors.zig")
	if err := os.WriteFile(outputPath, data, 0o644); err != nil {
		panic(err)
	}
	if err := writeCompiledFixtures(fixtureCases, compiledSystems); err != nil {
		panic(err)
	}
	if err := writeVerifyFixtures(fixtureCases, compiledSystems); err != nil {
		panic(err)
	}
}

func writeHeader(out *bytes.Buffer) {
	fmt.Fprintln(out, "// Code generated by verifier-ray/testdata/generate; DO NOT EDIT.")
	fmt.Fprintln(out)
	fmt.Fprintln(out, "pub const FieldCase = struct {")
	fmt.Fprintln(out, "    a: u32,")
	fmt.Fprintln(out, "    b: u32,")
	fmt.Fprintln(out, "    add: u32,")
	fmt.Fprintln(out, "    sub: u32,")
	fmt.Fprintln(out, "    mul: u32,")
	fmt.Fprintln(out, "    square_a: u32,")
	fmt.Fprintln(out, "    neg_a: u32,")
	fmt.Fprintln(out, "    has_inv_a: bool,")
	fmt.Fprintln(out, "    inv_a: u32,")
	fmt.Fprintln(out, "    has_div_ab: bool,")
	fmt.Fprintln(out, "    div_ab: u32,")
	fmt.Fprintln(out, "    bytes_a: [4]u8,")
	fmt.Fprintln(out, "};")
	fmt.Fprintln(out)
	fmt.Fprintln(out, "pub const ExtCase = struct {")
	fmt.Fprintln(out, "    a: [6]u32,")
	fmt.Fprintln(out, "    b: [6]u32,")
	fmt.Fprintln(out, "    scalar: u32,")
	fmt.Fprintln(out, "    add: [6]u32,")
	fmt.Fprintln(out, "    sub: [6]u32,")
	fmt.Fprintln(out, "    mul: [6]u32,")
	fmt.Fprintln(out, "    square_a: [6]u32,")
	fmt.Fprintln(out, "    neg_a: [6]u32,")
	fmt.Fprintln(out, "    mul_by_base: [6]u32,")
	fmt.Fprintln(out, "    has_inv_a: bool,")
	fmt.Fprintln(out, "    inv_a: [6]u32,")
	fmt.Fprintln(out, "    bytes_a: [24]u8,")
	fmt.Fprintln(out, "};")
	fmt.Fprintln(out)
	fmt.Fprintln(out, "pub const CanonicalBaseCase = struct { coeffs: []const u32, point: u32, expected: u32 };")
	fmt.Fprintln(out, "pub const CanonicalBaseAtExtCase = struct { coeffs: []const u32, point: [6]u32, expected: [6]u32 };")
	fmt.Fprintln(out, "pub const CanonicalExtAtBaseCase = struct { coeffs: []const [6]u32, point: u32, expected: [6]u32 };")
	fmt.Fprintln(out, "pub const CanonicalExtCase = struct { coeffs: []const [6]u32, point: [6]u32, expected: [6]u32 };")
	fmt.Fprintln(out, "pub const LagrangeBaseCase = CanonicalBaseCase;")
	fmt.Fprintln(out, "pub const LagrangeBaseAtExtCase = CanonicalBaseAtExtCase;")
	fmt.Fprintln(out, "pub const LagrangeExtAtBaseCase = CanonicalExtAtBaseCase;")
	fmt.Fprintln(out, "pub const LagrangeExtCase = CanonicalExtCase;")
	fmt.Fprintln(out)
	fmt.Fprintln(out, "pub const PoseidonCompressCase = struct { left: [8]u32, right: [8]u32, expected: [8]u32 };")
	fmt.Fprintln(out, "pub const PoseidonMdCase = struct { message: []const u32, expected: [8]u32 };")
	fmt.Fprintln(out, "pub const FiatShamirCase = struct { base_updates: []const u32, ext_updates: []const [6]u32, random_field: [8]u32, random_ext: [6]u32 };")
	fmt.Fprintln(out)
	fmt.Fprintf(out, "pub const prover_visibility_oracle: u8 = %d;\n", int(wiop.VisibilityOracle))
	fmt.Fprintf(out, "pub const prover_visibility_public: u8 = %d;\n", int(wiop.VisibilityPublic))
	fmt.Fprintln(out)
	fmt.Fprintln(out, "pub const RuntimeTraceColumn = union(enum) { oracle: []const [8]u32, public_base: []const u32, public_ext: []const [6]u32 };")
	fmt.Fprintln(out, "pub const RuntimeTraceCell = union(enum) { base: u32, ext: [6]u32 };")
	fmt.Fprintln(out, "pub const RuntimeTraceRound = struct { columns: []const RuntimeTraceColumn, cells: []const RuntimeTraceCell, expected_coins: []const [6]u32 };")
	fmt.Fprintln(out, "pub const RuntimeTraceCase = struct { rounds: []const RuntimeTraceRound };")
	fmt.Fprintln(out)
}

func writeFieldCases(out *bytes.Buffer) {
	rng := rand.New(rand.NewPCG(0x12345678, 0x9abcdef0))
	values := []field.Element{
		elem(0),
		elem(1),
		elem(2),
		elem(3),
		elem(koalaModulus - 1),
		elem(koalaModulus - 2),
		elem(uint64(field.RootOfUnity.Bits()[0])),
		elem(uint64(field.MontConstant.Bits()[0])),
	}
	for range 8 {
		values = append(values, field.PseudoRand(rng))
	}

	fmt.Fprintln(out, "pub const field_cases = [_]FieldCase{")
	for i := 0; i < len(values)-1; i++ {
		writeFieldCase(out, values[i], values[i+1])
	}
	fmt.Fprintln(out, "};")
	fmt.Fprintln(out)
}

func writeFieldCase(out *bytes.Buffer, a, b field.Element) {
	var add, sub, mul, square, neg, inv, div field.Element
	add.Add(&a, &b)
	sub.Sub(&a, &b)
	mul.Mul(&a, &b)
	square.Square(&a)
	neg.Neg(&a)

	hasInv := !a.IsZero()
	if hasInv {
		inv.Inverse(&a)
	}
	hasDiv := !b.IsZero()
	if hasDiv {
		div.Div(&a, &b)
	}

	fmt.Fprintf(out, "    .{ .a = %d, .b = %d, .add = %d, .sub = %d, .mul = %d, .square_a = %d, .neg_a = %d, .has_inv_a = %t, .inv_a = %d, .has_div_ab = %t, .div_ab = %d, .bytes_a = %s },\n",
		u(a), u(b), u(add), u(sub), u(mul), u(square), u(neg), hasInv, u(inv), hasDiv, u(div), bytes4(a.Bytes()))
}

func writeExtCases(out *bytes.Buffer) {
	rng := rand.New(rand.NewPCG(0x11111111, 0x22222222))
	values := []field.Ext{
		field.UintsToExt(0, 0, 0, 0, 0, 0),
		field.UintsToExt(1, 0, 0, 0, 0, 0),
		field.UintsToExt(0, 1, 0, 0, 0, 0),
		field.UintsToExt(0, 0, 1, 0, 0, 0),
		field.UintsToExt(0, 0, 0, 1, 0, 0),
		field.UintsToExt(0, 0, 0, 0, 1, 0),
		field.UintsToExt(0, 0, 0, 0, 0, 1),
		field.UintsToExt(1, 2, 3, 4, 5, 6),
		field.UintsToExt(koalaModulus-1, koalaModulus-2, 7, 11, 13, 17),
	}
	for range 6 {
		values = append(values, field.PseudoRandExt(rng))
	}

	scalars := []field.Element{elem(0), elem(1), elem(2), elem(17), elem(koalaModulus - 1)}

	fmt.Fprintln(out, "pub const ext_cases = [_]ExtCase{")
	for i := 0; i < len(values)-1; i++ {
		writeExtCase(out, values[i], values[i+1], scalars[i%len(scalars)])
	}
	fmt.Fprintln(out, "};")
	fmt.Fprintln(out)
}

func writeExtCase(out *bytes.Buffer, a, b field.Ext, scalar field.Element) {
	var add, sub, mul, square, neg, byBase, inv field.Ext
	add.Add(&a, &b)
	sub.Sub(&a, &b)
	mul.Mul(&a, &b)
	square.Square(&a)
	neg.Neg(&a)
	byBase.MulByElement(&a, &scalar)

	hasInv := !a.IsZero()
	if hasInv {
		inv.Inverse(&a)
	}

	bytesA := field.ExtToBytes(&a)
	fmt.Fprintf(out, "    .{ .a = %s, .b = %s, .scalar = %d, .add = %s, .sub = %s, .mul = %s, .square_a = %s, .neg_a = %s, .mul_by_base = %s, .has_inv_a = %t, .inv_a = %s, .bytes_a = %s },\n",
		ext6(a), ext6(b), u(scalar), ext6(add), ext6(sub), ext6(mul), ext6(square), ext6(neg), ext6(byBase), hasInv, ext6(inv), bytes24(bytesA))
}

func writePolynomialCases(out *bytes.Buffer) {
	basePolyA := []field.Element{elem(0), elem(1), elem(koalaModulus - 1), elem(17), elem(123456)}
	basePolyB := []field.Element{elem(9), elem(8), elem(7), elem(6)}
	extPolyA := []field.Ext{
		field.UintsToExt(1, 2, 3, 4, 5, 6),
		field.UintsToExt(0, 1, 0, 1, 2, 3),
		field.UintsToExt(9, 0, 8, 0, 4, 5),
		field.UintsToExt(11, 12, 13, 14, 6, 7),
	}
	extPolyB := []field.Ext{
		field.UintsToExt(4, 3, 2, 1, 5, 6),
		field.UintsToExt(5, 0, 0, 6, 7, 8),
		field.UintsToExt(7, 8, 9, 10, 11, 12),
	}

	basePoint := elem(5)
	basePoint2 := elem(19)
	extPoint := field.UintsToExt(5, 1, 7, 2, 3, 4)
	extPoint2 := field.UintsToExt(13, 3, 0, 4, 5, 6)

	fmt.Fprintln(out, "pub const canonical_base_cases = [_]CanonicalBaseCase{")
	writeCanonicalBaseCase(out, basePolyA, basePoint)
	writeCanonicalBaseCase(out, basePolyB, basePoint2)
	fmt.Fprintln(out, "};")
	fmt.Fprintln(out)

	fmt.Fprintln(out, "pub const canonical_base_at_ext_cases = [_]CanonicalBaseAtExtCase{")
	writeCanonicalBaseAtExtCase(out, basePolyA, extPoint)
	writeCanonicalBaseAtExtCase(out, basePolyB, extPoint2)
	fmt.Fprintln(out, "};")
	fmt.Fprintln(out)

	fmt.Fprintln(out, "pub const canonical_ext_at_base_cases = [_]CanonicalExtAtBaseCase{")
	writeCanonicalExtAtBaseCase(out, extPolyA, basePoint)
	writeCanonicalExtAtBaseCase(out, extPolyB, basePoint2)
	fmt.Fprintln(out, "};")
	fmt.Fprintln(out)

	fmt.Fprintln(out, "pub const canonical_ext_cases = [_]CanonicalExtCase{")
	writeCanonicalExtCase(out, extPolyA, extPoint)
	writeCanonicalExtCase(out, extPolyB, extPoint2)
	fmt.Fprintln(out, "};")
	fmt.Fprintln(out)

	lagrangeBase := []field.Element{elem(3), elem(1), elem(4), elem(1)}
	lagrangeExt := []field.Ext{
		field.UintsToExt(3, 1, 4, 1, 5, 9),
		field.UintsToExt(5, 9, 2, 6, 5, 3),
		field.UintsToExt(5, 3, 5, 8, 9, 7),
		field.UintsToExt(9, 7, 9, 3, 2, 3),
	}
	lagrangeBasePoint := elem(7)
	lagrangeExtPoint := field.UintsToExt(7, 2, 0, 1, 4, 5)

	fmt.Fprintln(out, "pub const lagrange_base_cases = [_]LagrangeBaseCase{")
	writeLagrangeBaseCase(out, lagrangeBase, lagrangeBasePoint)
	fmt.Fprintln(out, "};")
	fmt.Fprintln(out)

	fmt.Fprintln(out, "pub const lagrange_base_at_ext_cases = [_]LagrangeBaseAtExtCase{")
	writeLagrangeBaseAtExtCase(out, lagrangeBase, lagrangeExtPoint)
	fmt.Fprintln(out, "};")
	fmt.Fprintln(out)

	fmt.Fprintln(out, "pub const lagrange_ext_at_base_cases = [_]LagrangeExtAtBaseCase{")
	writeLagrangeExtAtBaseCase(out, lagrangeExt, lagrangeBasePoint)
	fmt.Fprintln(out, "};")
	fmt.Fprintln(out)

	fmt.Fprintln(out, "pub const lagrange_ext_cases = [_]LagrangeExtCase{")
	writeLagrangeExtCase(out, lagrangeExt, lagrangeExtPoint)
	fmt.Fprintln(out, "};")
	fmt.Fprintln(out)
}

func writeCanonicalBaseCase(out *bytes.Buffer, coeffs []field.Element, point field.Element) {
	res := polynomials.EvalCanonical(field.VecFromBase(coeffs), field.ElemFromBase(point))
	fmt.Fprintf(out, "    .{ .coeffs = &%s, .point = %d, .expected = %d },\n", elemSlice(coeffs), u(point), u(res.AsBase()))
}

func writeCanonicalBaseAtExtCase(out *bytes.Buffer, coeffs []field.Element, point field.Ext) {
	res := polynomials.EvalCanonical(field.VecFromBase(coeffs), field.ElemFromExt(point))
	fmt.Fprintf(out, "    .{ .coeffs = &%s, .point = %s, .expected = %s },\n", elemSlice(coeffs), ext6(point), ext6(res.AsExt()))
}

func writeCanonicalExtAtBaseCase(out *bytes.Buffer, coeffs []field.Ext, point field.Element) {
	res := polynomials.EvalCanonical(field.VecFromExt(coeffs), field.ElemFromBase(point))
	fmt.Fprintf(out, "    .{ .coeffs = &%s, .point = %d, .expected = %s },\n", extSlice(coeffs), u(point), ext6(res.AsExt()))
}

func writeCanonicalExtCase(out *bytes.Buffer, coeffs []field.Ext, point field.Ext) {
	res := polynomials.EvalCanonical(field.VecFromExt(coeffs), field.ElemFromExt(point))
	fmt.Fprintf(out, "    .{ .coeffs = &%s, .point = %s, .expected = %s },\n", extSlice(coeffs), ext6(point), ext6(res.AsExt()))
}

func writeLagrangeBaseCase(out *bytes.Buffer, values []field.Element, point field.Element) {
	res := polynomials.EvalLagrange(field.VecFromBase(values), field.ElemFromBase(point))
	fmt.Fprintf(out, "    .{ .coeffs = &%s, .point = %d, .expected = %d },\n", elemSlice(values), u(point), u(res.AsBase()))
}

func writeLagrangeBaseAtExtCase(out *bytes.Buffer, values []field.Element, point field.Ext) {
	res := polynomials.EvalLagrange(field.VecFromBase(values), field.ElemFromExt(point))
	fmt.Fprintf(out, "    .{ .coeffs = &%s, .point = %s, .expected = %s },\n", elemSlice(values), ext6(point), ext6(res.AsExt()))
}

func writeLagrangeExtAtBaseCase(out *bytes.Buffer, values []field.Ext, point field.Element) {
	res := polynomials.EvalLagrange(field.VecFromExt(values), field.ElemFromBase(point))
	fmt.Fprintf(out, "    .{ .coeffs = &%s, .point = %d, .expected = %s },\n", extSlice(values), u(point), ext6(res.AsExt()))
}

func writeLagrangeExtCase(out *bytes.Buffer, values []field.Ext, point field.Ext) {
	res := polynomials.EvalLagrange(field.VecFromExt(values), field.ElemFromExt(point))
	fmt.Fprintf(out, "    .{ .coeffs = &%s, .point = %s, .expected = %s },\n", extSlice(values), ext6(point), ext6(res.AsExt()))
}

func writePoseidonCases(out *bytes.Buffer) {
	leftA := octuplet(0, 1, 2, 3, 4, 5, 6, 7)
	rightA := octuplet(8, 9, 10, 11, 12, 13, 14, 15)
	leftB := octuplet(koalaModulus-1, koalaModulus-2, 17, 19, 23, 29, 31, 37)
	rightB := octuplet(41, 43, 47, 53, 59, 61, 67, 71)

	fmt.Fprintln(out, "pub const poseidon_compress_cases = [_]PoseidonCompressCase{")
	writePoseidonCompressCase(out, leftA, rightA)
	writePoseidonCompressCase(out, leftB, rightB)
	fmt.Fprintln(out, "};")
	fmt.Fprintln(out)

	fmt.Fprintln(out, "pub const poseidon_md_cases = [_]PoseidonMdCase{")
	writePoseidonMdCase(out, nil)
	writePoseidonMdCase(out, []field.Element{elem(1)})
	writePoseidonMdCase(out, []field.Element{elem(1), elem(2), elem(3), elem(4), elem(5), elem(6), elem(7)})
	writePoseidonMdCase(out, []field.Element{elem(1), elem(2), elem(3), elem(4), elem(5), elem(6), elem(7), elem(8)})
	writePoseidonMdCase(out, []field.Element{elem(1), elem(2), elem(3), elem(4), elem(5), elem(6), elem(7), elem(8), elem(9)})
	fmt.Fprintln(out, "};")
	fmt.Fprintln(out)
}

func writePoseidonCompressCase(out *bytes.Buffer, left, right field.Octuplet) {
	res := poseidon2.Compress(left, right)
	fmt.Fprintf(out, "    .{ .left = %s, .right = %s, .expected = %s },\n", oct8(left), oct8(right), oct8(res))
}

func writePoseidonMdCase(out *bytes.Buffer, msg []field.Element) {
	h := poseidon2.NewMDHasher()
	h.WriteElements(msg...)
	res := h.SumDigest()
	fmt.Fprintf(out, "    .{ .message = &%s, .expected = %s },\n", elemSlice(msg), oct8(res))
}

func writeFiatShamirCases(out *bytes.Buffer) {
	fmt.Fprintln(out, "pub const fiat_shamir_cases = [_]FiatShamirCase{")
	writeFiatShamirCase(out,
		[]field.Element{elem(3), elem(4), elem(5)},
		[]field.Ext{field.UintsToExt(1, 2, 3, 4, 5, 6)},
	)
	writeFiatShamirCase(out,
		[]field.Element{elem(koalaModulus - 1), elem(9)},
		[]field.Ext{field.UintsToExt(5, 0, 6, 0, 7, 8), field.UintsToExt(7, 8, 9, 10, 11, 12)},
	)
	fmt.Fprintln(out, "};")
	fmt.Fprintln(out)
}

func writeFiatShamirCase(out *bytes.Buffer, baseUpdates []field.Element, extUpdates []field.Ext) {
	fs := fiatshamir.NewFiatShamir()
	fs.Update(baseUpdates...)
	fs.UpdateExt(extUpdates...)
	randomDigest := fs.RandomDigest()
	randomExt := fs.RandomFext()
	fmt.Fprintf(out, "    .{ .base_updates = &%s, .ext_updates = &%s, .random_field = %s, .random_ext = %s },\n",
		elemSlice(baseUpdates), extSlice(extUpdates), oct8(randomDigest), ext6(randomExt))
}

type runtimeTraceCase struct {
	rounds []runtimeTraceRound
}

// runtimeTraceRound is the verifier-visible transcript input for one WIOP
// round. expectedCoins are the extension-field coins that prover-ray derives for
// the next round after absorbing this round's columns and cells.
type runtimeTraceRound struct {
	columns       []runtimeTraceColumn
	cells         []runtimeTraceCell
	expectedCoins []field.Ext
}

// runtimeTraceColumn records one verifier-visible column assignment. prover-ray
// may have internal columns in the source protocol, but they are intentionally
// not exported to verifier-ray traces.
type runtimeTraceColumn struct {
	commitments      []field.Octuplet
	publicBaseValues []field.Element
	publicExtValues  []field.Ext
}

// runtimeTraceCell records a scalar value opened in the round. Unlike internal
// columns, cells are always verifier-visible in prover-ray AdvanceRound and must
// be assigned.
type runtimeTraceCell struct {
	baseValue *field.Element
	extValue  *field.Ext
}

// writeRuntimeTraceCases emits the scripted multi-round WIOP trace used by
// verifier-ray to prove that per-round Fiat-Shamir coin derivation matches
// prover-ray.
func writeRuntimeTraceCases(out *bytes.Buffer) {
	fmt.Fprintln(out, "pub const runtime_trace_cases = [_]RuntimeTraceCase{")
	for _, tc := range buildRuntimeTraceCases() {
		fmt.Fprintln(out, "    .{ .rounds = &.{")
		for _, round := range tc.rounds {
			writeRuntimeTraceRound(out, round)
		}
		fmt.Fprintln(out, "    } },")
	}
	fmt.Fprintln(out, "};")
	fmt.Fprintln(out)
}

// buildRuntimeTraceCases constructs a small prover-ray WIOP runtime at the
// verifier boundary. Oracle columns are represented by their commitment values
// rather than raw witness assignments, and expected coins are sampled through
// Runtime.AdvanceRound so the fixture stays coupled to prover-ray round logic.
func buildRuntimeTraceCases() []runtimeTraceCase {
	sys := wiop.NewSystemf("runtime-trace")
	r0 := sys.NewRound()
	r1 := sys.NewRound()
	r2 := sys.NewRound()
	commitmentMod := sys.NewSizedModule(sys.Context.Childf("commitments"), len(field.Octuplet{}), wiop.PaddingDirectionNone)
	valueMod := sys.NewSizedModule(sys.Context.Childf("values"), 4, wiop.PaddingDirectionNone)

	r0OracleCommitmentColumn := commitmentMod.NewColumn(sys.Context.Childf("r0-oracle-commitment"), wiop.VisibilityOracle, r0)
	r0PublicExt := valueMod.NewExtensionColumn(sys.Context.Childf("r0-public-ext"), wiop.VisibilityPublic, r0)
	// Keep an unassigned internal column in the prover-ray protocol. It is not a
	// verifier-visible transcript message and is intentionally not exported.
	commitmentMod.NewColumn(sys.Context.Childf("r0-internal-unassigned"), wiop.VisibilityInternal, r0)
	r0BaseCell := r0.NewCell(sys.Context.Childf("r0-base-cell"), false)
	r0ExtCell := r0.NewCell(sys.Context.Childf("r0-ext-cell"), true)

	r1CoinA := r1.NewCoinField(sys.Context.Childf("r1-coin-a"))
	r1CoinB := r1.NewCoinField(sys.Context.Childf("r1-coin-b"))
	r1OracleCommitmentColumn := commitmentMod.NewColumn(sys.Context.Childf("r1-oracle-commitment"), wiop.VisibilityOracle, r1)
	r1PublicBase := valueMod.NewColumn(sys.Context.Childf("r1-public-base"), wiop.VisibilityPublic, r1)
	r1BaseCell := r1.NewCell(sys.Context.Childf("r1-base-cell"), false)

	r2Coin := r2.NewCoinField(sys.Context.Childf("r2-coin"))

	r0OracleBaseValues := elems(3, 1, 4, 1)
	r0OracleCommitment := commitmentFromElements(r0OracleBaseValues)
	r0PublicExtValues := []field.Ext{
		field.UintsToExt(5, 9, 2, 6, 5, 3),
		field.UintsToExt(5, 8, 9, 7, 9, 3),
		field.UintsToExt(2, 3, 8, 4, 6, 2),
		field.UintsToExt(6, 4, 3, 3, 8, 3),
	}
	r0BaseCellValue := elem(23)
	r0ExtCellValue := field.UintsToExt(10, 20, 30, 40, 50, 60)

	r1OracleExtValues := []field.Ext{
		field.UintsToExt(101, 102, 103, 104, 105, 106),
		field.UintsToExt(201, 202, 203, 204, 205, 206),
		field.UintsToExt(301, 302, 303, 304, 305, 306),
		field.UintsToExt(401, 402, 403, 404, 405, 406),
	}
	r1OracleCommitment := commitmentFromExts(r1OracleExtValues)
	r1PublicBaseValues := elems(11, 22, 33, 44)
	r1BaseCellValue := elem(77)

	rt := wiop.NewRuntime(sys)
	rt.AssignColumn(r0OracleCommitmentColumn, concreteBase(r0OracleCommitment[:]))
	rt.AssignColumn(r0PublicExt, concreteExt(r0PublicExtValues))
	rt.AssignCell(r0BaseCell, field.ElemFromBase(r0BaseCellValue))
	rt.AssignCell(r0ExtCell, field.ElemFromExt(r0ExtCellValue))
	rt.AdvanceRound()
	r1Coins := []field.Ext{
		rt.GetCoinValue(r1CoinA).AsExt(),
		rt.GetCoinValue(r1CoinB).AsExt(),
	}

	rt.AssignColumn(r1OracleCommitmentColumn, concreteBase(r1OracleCommitment[:]))
	rt.AssignColumn(r1PublicBase, concreteBase(r1PublicBaseValues))
	rt.AssignCell(r1BaseCell, field.ElemFromBase(r1BaseCellValue))
	rt.AdvanceRound()
	r2Coins := []field.Ext{rt.GetCoinValue(r2Coin).AsExt()}

	return []runtimeTraceCase{{
		rounds: []runtimeTraceRound{
			{
				columns: []runtimeTraceColumn{
					{commitments: []field.Octuplet{r0OracleCommitment}},
					{publicExtValues: r0PublicExtValues},
				},
				cells: []runtimeTraceCell{
					baseTraceCell(r0BaseCellValue),
					extTraceCell(r0ExtCellValue),
				},
				expectedCoins: r1Coins,
			},
			{
				columns: []runtimeTraceColumn{
					{commitments: []field.Octuplet{r1OracleCommitment}},
					{publicBaseValues: r1PublicBaseValues},
				},
				cells: []runtimeTraceCell{
					baseTraceCell(r1BaseCellValue),
				},
				expectedCoins: r2Coins,
			},
		},
	}}
}

func writeRuntimeTraceRound(out *bytes.Buffer, round runtimeTraceRound) {
	fmt.Fprintln(out, "        .{")
	fmt.Fprintln(out, "            .columns = &.{")
	for _, column := range round.columns {
		writeTraceColumn(out, column, "                ")
	}
	fmt.Fprintln(out, "            },")
	fmt.Fprintln(out, "            .cells = &.{")
	for _, cell := range round.cells {
		writeTraceCell(out, cell, "                ")
	}
	fmt.Fprintln(out, "            },")
	fmt.Fprintf(out, "            .expected_coins = &%s,\n", extSlice(round.expectedCoins))
	fmt.Fprintln(out, "        },")
}

func baseTraceCell(value field.Element) runtimeTraceCell {
	return runtimeTraceCell{baseValue: &value}
}

func extTraceCell(value field.Ext) runtimeTraceCell {
	return runtimeTraceCell{extValue: &value}
}

type fixtureCase struct {
	name    string
	honest  vanishingProofView
	invalid *vanishingProofView
	// honestPcs and invalidPcs carry the runtime PCS openings for the honest and
	// invalid proofs. The matching FRI opening proofs come from the proving
	// runtime.
	honestPcs     *codegen.PcsSystem
	invalidPcs    *codegen.PcsSystem
	honestOpening fri.OpeningProof
	invalidOpen   fri.OpeningProof
	// alt is a second honest proof of the same compiled protocol at a different
	// dynamic-module size, verified against the same baked PcsSystem. altPcs is
	// the alt proof's runtime opening.
	alt     *vanishingProofView
	altPcs  *codegen.PcsSystem
	altOpen fri.OpeningProof
}

type vanishingProofView struct {
	rounds         []runtimeTraceRound
	witnessClaims  []field.Ext
	quotientClaims []field.Ext
	moduleSizes    []int
}

type assignFn func(rt *wiop.Runtime)

func compileFullPipeline(sys *wiop.System) {
	rangecheck.Compile(sys)
	lookuptologderivsum.Compile(sys)
	logderivativesum.Compile(sys)
	localvanishing.Compile(sys)
	global.Compile(sys)
	// PCS runs last, after the earlier passes have registered their columns and
	// LagrangeEval openings.
	pcscompiler.Compile(sys)
}

func buildCompiledFixtureCases() ([]fixtureCase, []codegen.CompiledSystem, error) {
	var cases []fixtureCase
	var systems []codegen.CompiledSystem

	add := func(source, name string, sys *wiop.System, honest assignFn, invalid assignFn) error {
		compileFullPipeline(sys)
		// Fail closed on any verifier action the codegen does not know how to emit.
		if err := codegen.AssertAllVerifierActionsHandled(sys); err != nil {
			return fmt.Errorf("verifier actions %s/%s: %w", source, name, err)
		}
		routing, err := codegen.BuildCoinRouting(sys)
		if err != nil {
			return fmt.Errorf("build coin routing %s/%s: %w", source, name, err)
		}
		vanishingSystem, err := codegen.BuildVanishingSystem(sys, routing)
		if err != nil {
			return fmt.Errorf("build vanishing system %s/%s: %w", source, name, err)
		}
		if len(vanishingSystem.Modules) == 0 {
			return nil
		}
		honestRt := runProver(sys, honest)
		logDeriv, err := codegen.BuildLogDerivSystem(sys)
		if err != nil {
			return fmt.Errorf("build logderiv system %s/%s: %w", source, name, err)
		}
		honestProof := extractVanishingProofView(sys, honestRt)

		tc := fixtureCase{name: name, honest: honestProof}
		if invalid != nil {
			invalidRt := runProver(sys, invalid)
			proof := extractVanishingProofView(sys, invalidRt)
			tc.invalid = &proof
			ip, err := codegen.BuildPcsSystem(sys, invalidRt, routing)
			if err != nil {
				return fmt.Errorf("build invalid pcs system %s/%s: %w", source, name, err)
			}
			if invalidRt.PCSOpeningProof == nil {
				return fmt.Errorf("pcs %s/%s: invalid runtime has no PCSOpeningProof", source, name)
			}
			tc.invalidPcs = &ip
			tc.invalidOpen = *invalidRt.PCSOpeningProof
		}

		honestPcs, err := codegen.BuildPcsSystem(sys, honestRt, routing)
		if err != nil {
			return fmt.Errorf("build pcs system %s/%s: %w", source, name, err)
		}
		if honestRt.PCSOpeningProof == nil {
			return fmt.Errorf("pcs %s/%s: honest runtime has no PCSOpeningProof", source, name)
		}
		tc.honestPcs = &honestPcs
		tc.honestOpening = *honestRt.PCSOpeningProof
		pcsSys := &honestPcs

		cases = append(cases, tc)
		systems = append(systems, codegen.CompiledSystem{Routing: routing, Vanishing: vanishingSystem, LogDeriv: logDeriv, Pcs: pcsSys})
		return nil
	}

	// addMultiSize emits one baked PcsSystem plus two honest proofs at different
	// runtime sizes.
	addMultiSize := func(source, name string, sys *wiop.System, honest, alt assignFn) error {
		compileFullPipeline(sys)
		if err := codegen.AssertAllVerifierActionsHandled(sys); err != nil {
			return fmt.Errorf("verifier actions %s/%s: %w", source, name, err)
		}
		routing, err := codegen.BuildCoinRouting(sys)
		if err != nil {
			return fmt.Errorf("build coin routing %s/%s: %w", source, name, err)
		}
		vanishingSystem, err := codegen.BuildVanishingSystem(sys, routing)
		if err != nil {
			return fmt.Errorf("build vanishing system %s/%s: %w", source, name, err)
		}
		logDeriv, err := codegen.BuildLogDerivSystem(sys)
		if err != nil {
			return fmt.Errorf("build logderiv system %s/%s: %w", source, name, err)
		}

		honestRt := runProver(sys, honest)
		honestPcs, err := codegen.BuildPcsSystem(sys, honestRt, routing)
		if err != nil {
			return fmt.Errorf("build pcs system %s/%s: %w", source, name, err)
		}
		if honestRt.PCSOpeningProof == nil {
			return fmt.Errorf("pcs %s/%s: honest runtime has no PCSOpeningProof", source, name)
		}

		altRt := runProver(sys, alt)
		// altPcs is used only to extract the alt proof's runtime opening.
		altPcs, err := codegen.BuildPcsSystem(sys, altRt, routing)
		if err != nil {
			return fmt.Errorf("build alt pcs system %s/%s: %w", source, name, err)
		}
		if altRt.PCSOpeningProof == nil {
			return fmt.Errorf("pcs %s/%s: alt runtime has no PCSOpeningProof", source, name)
		}

		tc := fixtureCase{
			name:          name,
			honest:        extractVanishingProofView(sys, honestRt),
			honestPcs:     &honestPcs,
			honestOpening: *honestRt.PCSOpeningProof,
		}
		altView := extractVanishingProofView(sys, altRt)
		tc.alt = &altView
		tc.altPcs = &altPcs
		tc.altOpen = *altRt.PCSOpeningProof

		cases = append(cases, tc)
		systems = append(systems, codegen.CompiledSystem{Routing: routing, Vanishing: vanishingSystem, LogDeriv: logDeriv, Pcs: &honestPcs})
		return nil
	}

	for _, factory := range wioptest.VanishingScenarios() {
		sc := factory()
		if err := add("Vanishing", sc.Name, sc.Sys, sc.AssignHonest, sc.AssignInvalid); err != nil {
			return nil, nil, err
		}
	}

	// Multi-size committed-dynamic coverage for one baked PcsSystem.
	if err := addMultiSizeDynFib(addMultiSize); err != nil {
		return nil, nil, err
	}
	// Two independent committed dynamic modules against one baked PcsSystem.
	if err := addMultiSizeTwoDynModules(addMultiSize); err != nil {
		return nil, nil, err
	}
	// LocalVanishing is intentionally NOT generated: at the verifier level every
	// LocalVanishing scenario reduces to a vanishing System whose shape (module
	// count, dynamic modules, batch count, empty logderiv) is a strict subset of
	// the Vanishing set above. The local-vanishing *compiler* is exercised by
	// prover-ray's own tests; the verifier sees nothing new here.
	for _, factory := range wioptest.LogDerivativeSumCompilerScenarios() {
		sc := factory()
		if err := add("LogDerivativeSumCompiler", sc.Name, sc.Sys, sc.AssignWitness, nil); err != nil {
			return nil, nil, err
		}
	}
	for _, factory := range wioptest.LookupScenarios() {
		sc := factory()
		if err := add("Lookup", sc.Name, sc.Sys, sc.AssignWitness, nil); err != nil {
			return nil, nil, err
		}
	}
	// Keep one RangeCheck scenario for the 3-module / 4-batch verifier shape
	// that Lookup does not produce.
	for _, factory := range wioptest.RangeCheckCompilerScenarios() {
		sc := factory()
		if sc.Name != "DistinctBounds" {
			continue
		}
		if err := add("RangeCheckCompiler", sc.Name, sc.Sys, sc.AssignWitness, nil); err != nil {
			return nil, nil, err
		}
	}

	// LagrangeSelector boundary scenario. It is constructed here rather than in
	// prover-ray's wioptest because it exercises the lagrange_selector codegen
	// and Zig evaluator path, which the pinned prover-ray module already
	// supports via wiop.NewLagrangeSelector; building it locally keeps the
	// fixture reproducible from the pinned module (see `make verify-testdata`).
	{
		sys, col := buildLagrangeSelectorBoundarySystem()
		honest := func(rt *wiop.Runtime) { rt.AssignColumn(col, concreteBase(elems(7, 99, 7, 7))) }
		invalid := func(rt *wiop.Runtime) { rt.AssignColumn(col, concreteBase(elems(7, 98, 7, 7))) }
		if err := add("Vanishing", "LagrangeSelectorBoundary", sys, honest, invalid); err != nil {
			return nil, nil, err
		}
	}

	// Dynamic-module variant of the LagrangeSelectorBoundary scenario. Its
	// module size is resolved at runtime (4, from the assigned column length),
	// so it drives the Zig verifier's dynamic selector branch that the static
	// fixture above leaves uncovered.
	{
		sys, col := buildDynamicLagrangeSelectorBoundarySystem()
		honest := func(rt *wiop.Runtime) { rt.AssignColumn(col, concreteBase(elems(7, 99, 7, 7))) }
		invalid := func(rt *wiop.Runtime) { rt.AssignColumn(col, concreteBase(elems(7, 98, 7, 7))) }
		if err := add("Vanishing", "DynamicLagrangeSelectorBoundary", sys, honest, invalid); err != nil {
			return nil, nil, err
		}
	}
	// Larger MultiColumn scenario for stress profiling.
	sys, honest := buildLookupMultiColumnBenchSystem()
	if err := add("Lookup", "MultiColumnBench", sys, honest, nil); err != nil {
		return nil, nil, err
	}

	return cases, systems, nil
}

// buildLookupMultiColumnBenchSystem is a verifier-ray-local stress fixture for
// profiling a wider lookup/log-derivative/vanishing pipeline. It stays local to
// verifier-ray because its purpose is benchmark shape, not reusable prover-ray
// scenario coverage.
func buildLookupMultiColumnBenchSystem() (*wiop.System, assignFn) {
	const (
		bigSize = 1 << 10
		numCols = 5
	)
	var (
		tCols        = make([]*wiop.Column, numCols)
		sCols        = make([]*wiop.Column, numCols)
		tTableView   = make([]*wiop.ColumnView, numCols)
		sTableView   = make([]*wiop.ColumnView, numCols)
		tAssignments = make([][]field.Element, numCols)
		sAssignments = make([][]field.Element, numCols)
	)

	sys := wiop.NewSystemf("lk-multi-col-bench")
	r0 := sys.NewRound()
	modT := sys.NewSizedModule(sys.Context.Childf("modT"), bigSize, wiop.PaddingDirectionNone)
	modS := sys.NewSizedModule(sys.Context.Childf("modS"), bigSize, wiop.PaddingDirectionNone)
	for i := range tCols {
		tCols[i] = modT.NewColumn(sys.Context.Childf("T%d", i), wiop.VisibilityOracle, r0)
		sCols[i] = modS.NewColumn(sys.Context.Childf("S%d", i), wiop.VisibilityOracle, r0)
		tTableView[i] = tCols[i].View()
		sTableView[i] = sCols[i].View()
	}
	sys.NewInclusion(
		sys.Context.Childf("inc-big-table-bench"),
		[]wiop.Table{wiop.NewTable(sTableView...)},
		[]wiop.Table{wiop.NewTable(tTableView...)},
	)

	for i := range tCols {
		tAssignments[i] = make([]field.Element, bigSize)
		sAssignments[i] = make([]field.Element, bigSize)
		for j := range bigSize {
			tAssignments[i][j] = elem(uint64(i + j + 1))
			sAssignments[i][j] = elem(uint64(i + (j % (bigSize / 2)) + 1))
		}
	}

	honest := func(rt *wiop.Runtime) {
		for i := range tCols {
			rt.AssignColumn(tCols[i], concreteBase(tAssignments[i]))
			rt.AssignColumn(sCols[i], concreteBase(sAssignments[i]))
		}
	}
	return sys, honest
}

// buildLagrangeSelectorBoundarySystem builds a size-4 module with the single
// vanishing L_1·(col − 99) = 0. The Lagrange selector L_1 is 1 at row 1 and 0
// elsewhere on the domain, so the constraint pins col[1] = 99 while leaving the
// other rows free. It exercises the verifier's out-of-domain selector
// evaluation L_1(r) = ω·(r⁴−1)/(4·(r−ω)). The column is returned so the caller
// can assign witnesses.
func buildLagrangeSelectorBoundarySystem() (*wiop.System, *wiop.Column) {
	sys := wiop.NewSystemf("lagrange-sel")
	r0 := sys.NewRound()
	mod := sys.NewSizedModule(sys.Context.Childf("mod"), 4, wiop.PaddingDirectionNone)
	col := mod.NewColumn(sys.Context.Childf("col"), wiop.VisibilityOracle, r0)
	selector := wiop.NewLagrangeSelector(mod, 1)
	value := wiop.NewConstantField(elem(99))
	mod.NewVanishing(sys.Context.Childf("boundary"), wiop.Mul(selector, wiop.Sub(col.View(), value)))
	return sys, col
}

// buildDynamicLagrangeSelectorBoundarySystem is the dynamic-module twin of
// buildLagrangeSelectorBoundarySystem: same L_1·(col − 99) = 0 constraint, but
// on a dynamic module whose domain size is fixed only at runtime (here 4, from
// the assigned column length). Because the module is unsized at codegen time,
// the Zig verifier takes the dynamic selector path — deriving ω from
// ctx.dynamic_n via field.rootOfUnityBy and computing ω^position at runtime —
// rather than folding ω^position to a comptime constant. The static fixture
// never exercises that branch, so this one guards the path production dynamic
// modules actually hit. The column is returned so the caller can assign
// witnesses.
func buildDynamicLagrangeSelectorBoundarySystem() (*wiop.System, *wiop.Column) {
	sys := wiop.NewSystemf("lagrange-sel-dyn")
	r0 := sys.NewRound()
	mod := sys.NewDynamicModule(sys.Context.Childf("mod"), wiop.PaddingDirectionRight)
	col := mod.NewColumn(sys.Context.Childf("col"), wiop.VisibilityOracle, r0)
	selector := wiop.NewLagrangeSelector(mod, 1)
	value := wiop.NewConstantField(elem(99))
	mod.NewVanishing(sys.Context.Childf("boundary"), wiop.Mul(selector, wiop.Sub(col.View(), value)))
	return sys, col
}

// runProver creates a runtime for sys, applies assign, advances all rounds
// running every prover action, and returns the completed runtime.
func runProver(sys *wiop.System, assign assignFn) *wiop.Runtime {
	rt := wiop.NewRuntime(sys)
	assign(rt)
	for _, action := range rt.CurrentRound().ProverActions {
		action.Run(rt)
	}
	for rt.CurrentRound().ID < len(rt.System.Rounds)-1 {
		rt.AdvanceRound()
		for _, action := range rt.CurrentRound().ProverActions {
			action.Run(rt)
		}
	}
	return rt
}

// extractVanishingProofView reads witness/quotient claims and round trace data
// from an already-completed runtime.
func extractVanishingProofView(sys *wiop.System, rt *wiop.Runtime) vanishingProofView {
	verifiers := globalVerifiers(sys)

	var witnessClaims []field.Ext
	var quotientClaims []field.Ext
	for _, verifier := range verifiers {
		for _, claim := range verifier.WitnessClaims {
			witnessClaims = append(witnessClaims, rt.GetCellValue(claim).AsExt())
		}
		for _, bucket := range verifier.Buckets {
			for _, claim := range bucket.QuotientClaims {
				quotientClaims = append(quotientClaims, rt.GetCellValue(claim).AsExt())
			}
		}
	}

	rounds := make([]runtimeTraceRound, 0, len(sys.Rounds)-1)
	for i := 0; i < len(sys.Rounds)-1; i++ {
		rounds = append(rounds, runtimeTraceRoundFromRuntime(rt, sys.Rounds[i]))
	}

	return vanishingProofView{
		rounds:         rounds,
		witnessClaims:  witnessClaims,
		quotientClaims: quotientClaims,
		moduleSizes:    dynamicModuleSizes(sys, rt),
	}
}

// addMultiSizeDynFib constructs the dyn-fib protocol (a single committed dynamic
// column with the Fibonacci recurrence A[i] − A[i−1] − A[i−2] = 0) and registers
// it via `reg` (addMultiSize) with two honest witnesses of DIFFERENT lengths
// (8 and 16). Rows 0 and 1 are auto-cancelled by the back-shifts, so any
// Fibonacci prefix is valid. This exercises verifying two dynamic sizes against
// one baked PcsSystem.
func addMultiSizeDynFib(reg func(source, name string, sys *wiop.System, honest, alt assignFn) error) error {
	sys := wiop.NewSystemf("dyn-fib-multisize")
	r0 := sys.NewRound()
	mod := sys.NewDynamicModule(sys.Context.Childf("mod"), wiop.PaddingDirectionRight)
	col := mod.NewColumn(sys.Context.Childf("col"), wiop.VisibilityOracle, r0)
	mod.NewVanishing(
		sys.Context.Childf("fib"),
		wiop.Sub(
			wiop.Sub(col.View(), col.View().Shift(-1)),
			col.View().Shift(-2),
		),
	)

	honest := func(rt *wiop.Runtime) { rt.AssignColumn(col, fibVector(8)) }
	alt := func(rt *wiop.Runtime) { rt.AssignColumn(col, fibVector(16)) }
	return reg("MultiSize", "DynamicFibonacciMultiSize", sys, honest, alt)
}

// fibVector builds a length-n Fibonacci column (rows 0 and 1 = 1), used as an
// honest witness for the committed-dynamic Fibonacci recurrence.
func fibVector(n int) *wiop.ConcreteVector {
	vals := make([]uint64, n)
	vals[0], vals[1] = 1, 1
	for i := 2; i < n; i++ {
		vals[i] = vals[i-1] + vals[i-2]
	}
	elems := make([]field.Element, n)
	for i, v := range vals {
		elems[i].SetUint64(v)
	}
	return &wiop.ConcreteVector{Plain: field.VecFromBase(elems)}
}

// addMultiSizeTwoDynModules builds a protocol with TWO independent committed
// dynamic modules (each a Fibonacci column), proven at two size configurations
// against ONE baked PcsSystem. The alt witness resizes BOTH modules to different
// lengths than honest, so the verifier must (a) absorb each module's size into
// the transcript in sys.Modules order, (b) index module_sizes[i] per dynamic
// module correctly, and (c) reconstruct two independently-sized layouts that
// coexist in the shared column schedule. Single-module scenarios cannot catch a
// swapped module index or a cross-module absorption-order bug — this one does.
func addMultiSizeTwoDynModules(reg func(source, name string, sys *wiop.System, honest, alt assignFn) error) error {
	sys := wiop.NewSystemf("dyn-fib-two-modules")
	r0 := sys.NewRound()

	modA := sys.NewDynamicModule(sys.Context.Childf("modA"), wiop.PaddingDirectionRight)
	colA := modA.NewColumn(sys.Context.Childf("colA"), wiop.VisibilityOracle, r0)
	modA.NewVanishing(
		sys.Context.Childf("fibA"),
		wiop.Sub(wiop.Sub(colA.View(), colA.View().Shift(-1)), colA.View().Shift(-2)),
	)

	modB := sys.NewDynamicModule(sys.Context.Childf("modB"), wiop.PaddingDirectionRight)
	colB := modB.NewColumn(sys.Context.Childf("colB"), wiop.VisibilityOracle, r0)
	modB.NewVanishing(
		sys.Context.Childf("fibB"),
		wiop.Sub(wiop.Sub(colB.View(), colB.View().Shift(-1)), colB.View().Shift(-2)),
	)

	// honest: A at 8, B at 16. alt: A at 16, B at 8 — both modules change size AND
	// their relative sizes swap, so an off-by-one module index would derive wrong
	// coins and reject an honest proof.
	honest := func(rt *wiop.Runtime) {
		rt.AssignColumn(colA, fibVector(8))
		rt.AssignColumn(colB, fibVector(16))
	}
	alt := func(rt *wiop.Runtime) {
		rt.AssignColumn(colA, fibVector(16))
		rt.AssignColumn(colB, fibVector(8))
	}
	return reg("MultiSize", "DynamicFibonacciTwoModules", sys, honest, alt)
}

func globalVerifiers(sys *wiop.System) []*global.Verifier {
	var verifiers []*global.Verifier
	for _, round := range sys.Rounds {
		for _, action := range round.VerifierActions {
			if verifier, ok := action.(*global.Verifier); ok {
				verifiers = append(verifiers, verifier)
			}
		}
	}
	return verifiers
}

// dynamicModuleSizes builds the proof's `module_sizes` slice in the canonical
// dynamic-module order (sys.Modules order — see codegen.DynamicModuleOrder),
// which is the order prover-ray's AdvanceRound absorbs the sizes and the order
// every DynamicIndex points into. `out[i]` is the runtime size of the i-th
// dynamic module in that order.
func dynamicModuleSizes(sys *wiop.System, rt *wiop.Runtime) []int {
	order := codegen.DynamicModuleOrder(sys)
	out := make([]int, len(order))
	for i, module := range order {
		out[i] = module.RuntimeSize(rt)
	}
	return out
}

func runtimeTraceRoundFromRuntime(rt *wiop.Runtime, round *wiop.Round) runtimeTraceRound {
	var trace runtimeTraceRound
	// A committed (interactive PCS) round carries its Merkle root as a single
	// oracle commitment, absorbed by the verifier in place of the now-hidden
	// columns — mirroring prover-ray's AdvanceRound. This is the octuplet the PCS
	// batch root binds to (see codegen.PcsBatchRoot / verifier.resolveRoots).
	if round.HasCommitment {
		root, ok := rt.Commitments[round.ID]
		if !ok {
			panic(fmt.Sprintf("round %d HasCommitment but no root in runtime", round.ID))
		}
		trace.columns = append(trace.columns, runtimeTraceColumn{commitments: []field.Octuplet{root}})
	}
	for _, col := range round.Columns {
		if col.Visibility < wiop.VisibilityOracle || !rt.HasColumnAssignment(col) {
			continue
		}
		vec := rt.GetColumnAssignment(col).Plain
		if vec.IsBase() {
			trace.columns = append(trace.columns, runtimeTraceColumn{publicBaseValues: append([]field.Element(nil), vec.AsBase()...)})
		} else {
			trace.columns = append(trace.columns, runtimeTraceColumn{publicExtValues: append([]field.Ext(nil), vec.AsExt()...)})
		}
	}
	for _, cell := range round.Cells {
		if !rt.HasCellValue(cell) {
			continue
		}
		value := rt.GetCellValue(cell)
		if value.IsBase() {
			trace.cells = append(trace.cells, baseTraceCell(value.AsBase()))
		} else {
			trace.cells = append(trace.cells, extTraceCell(value.AsExt()))
		}
	}
	return trace
}

func writeCompiledFixtures(cases []fixtureCase, systems []codegen.CompiledSystem) error {
	var out bytes.Buffer
	writeCompiledHeader(&out)
	opts := codegen.CompiledSystemZigOptions{
		EmitHeader:      false,
		ProtocolImport:  "verifier_ray.protocol",
		FieldImport:     "verifier_ray.field.koalabear",
		VanishingImport: "verifier_ray.query.vanishing",
		LogDerivImport:  "verifier_ray.query.logderivativesum",
	}
	for i := range cases {
		if err := codegen.WriteCompiledSystemZig(&out, i, systems[i], opts); err != nil {
			return err
		}
		writeCompiledScenario(&out, i, cases[i])
	}
	writeCompiledScenarioList(&out, len(cases))

	data := out.Bytes()
	zigfmt, err := runZigFmt(data)
	if err == nil {
		data = zigfmt
	}
	return os.WriteFile(filepath.Join("..", "generated", "vanishing.zig"), data, 0o644)
}

func writeCompiledHeader(out *bytes.Buffer) {
	fmt.Fprintln(out, "// Code generated by verifier-ray/testdata/generate; DO NOT EDIT.")
	fmt.Fprintln(out)
	fmt.Fprintln(out, "const verifier_ray = @import(\"verifier_ray\");")
	fmt.Fprintln(out, "const field = verifier_ray.field.koalabear;")
	fmt.Fprintln(out, "const protocol = verifier_ray.protocol;")
	fmt.Fprintln(out, "const vanishing = verifier_ray.query.vanishing;")
	fmt.Fprintln(out, "const logderivativesum = verifier_ray.query.logderivativesum;")
	fmt.Fprintln(out)
	fmt.Fprintln(out, "pub const RuntimeTraceColumn = union(enum) { oracle: []const [8]u32, public_base: []const u32, public_ext: []const [6]u32 };")
	fmt.Fprintln(out, "pub const RuntimeTraceCell = union(enum) { base: u32, ext: [6]u32 };")
	fmt.Fprintln(out, "pub const RuntimeTraceRound = struct { columns: []const RuntimeTraceColumn, cells: []const RuntimeTraceCell };")
	fmt.Fprintln(out, "pub const VanishingProofView = struct { rounds: []const RuntimeTraceRound, witness_claims: []const [6]u32, quotient_claims: []const [6]u32, module_sizes: []const usize };")
	fmt.Fprintln(out, "pub const Scenario = struct { name: []const u8, spec: protocol.Spec, system: vanishing.System, logderiv: logderivativesum.System = .{}, honest: VanishingProofView, invalid: ?VanishingProofView = null };")
	fmt.Fprintln(out)
}

func writeCompiledScenario(out *bytes.Buffer, idx int, tc fixtureCase) {
	fmt.Fprintf(out, "const scenario_%d = Scenario{\n", idx)
	fmt.Fprintf(out, "    .name = \"%s\",\n", codegen.ZigString(tc.name))
	fmt.Fprintf(out, "    .spec = system_%d_spec,\n", idx)
	fmt.Fprintf(out, "    .system = system_%d,\n", idx)
	fmt.Fprintf(out, "    .logderiv = system_%d_logderiv,\n", idx)
	fmt.Fprintln(out, "    .honest =")
	writeVanishingProofView(out, tc.honest, "        ")
	if tc.invalid != nil {
		fmt.Fprintln(out, "    .invalid =")
		writeVanishingProofView(out, *tc.invalid, "        ")
	}
	fmt.Fprintln(out, "};")
	fmt.Fprintln(out)
}

func writeCompiledScenarioList(out *bytes.Buffer, count int) {
	fmt.Fprintln(out, "pub const scenarios = [_]Scenario{")
	for i := range count {
		fmt.Fprintf(out, "    scenario_%d,\n", i)
	}
	fmt.Fprintln(out, "};")
}

func writeVanishingProofView(out *bytes.Buffer, proof vanishingProofView, indent string) {
	fmt.Fprintf(out, "%s.{\n", indent)
	fmt.Fprintf(out, "%s    .rounds = &.{\n", indent)
	for _, round := range proof.rounds {
		writeTraceRound(out, round, indent+"        ")
	}
	fmt.Fprintf(out, "%s    },\n", indent)
	fmt.Fprintf(out, "%s    .witness_claims = &%s,\n", indent, extSlice(proof.witnessClaims))
	fmt.Fprintf(out, "%s    .quotient_claims = &%s,\n", indent, extSlice(proof.quotientClaims))
	fmt.Fprintf(out, "%s    .module_sizes = &%s,\n", indent, codegen.IntSlice(proof.moduleSizes))
	fmt.Fprintf(out, "%s},\n", indent)
}

func writeTraceRound(out *bytes.Buffer, round runtimeTraceRound, indent string) {
	fmt.Fprintf(out, "%s.{\n", indent)
	fmt.Fprintf(out, "%s    .columns = &.{\n", indent)
	for _, column := range round.columns {
		writeTraceColumn(out, column, indent+"        ")
	}
	fmt.Fprintf(out, "%s    },\n", indent)
	fmt.Fprintf(out, "%s    .cells = &.{\n", indent)
	for _, cell := range round.cells {
		writeTraceCell(out, cell, indent+"        ")
	}
	fmt.Fprintf(out, "%s    },\n", indent)
	fmt.Fprintf(out, "%s},\n", indent)
}

func writeTraceColumn(out *bytes.Buffer, column runtimeTraceColumn, indent string) {
	switch {
	case column.commitments != nil:
		fmt.Fprintf(out, "%s.{ .oracle = &%s },\n", indent, commitmentSlice(column.commitments))
	case column.publicBaseValues != nil:
		fmt.Fprintf(out, "%s.{ .public_base = &%s },\n", indent, elemSlice(column.publicBaseValues))
	case column.publicExtValues != nil:
		fmt.Fprintf(out, "%s.{ .public_ext = &%s },\n", indent, extSlice(column.publicExtValues))
	default:
		panic("runtime trace column has no data variant")
	}
}

func writeTraceCell(out *bytes.Buffer, cell runtimeTraceCell, indent string) {
	switch {
	case cell.baseValue != nil:
		fmt.Fprintf(out, "%s.{ .base = %d },\n", indent, u(*cell.baseValue))
	case cell.extValue != nil:
		fmt.Fprintf(out, "%s.{ .ext = %s },\n", indent, ext6(*cell.extValue))
	default:
		panic("runtime trace cell has no data variant")
	}
}

func writeVerifyFixtures(allCases []fixtureCase, allSystems []codegen.CompiledSystem) error {
	// verify.zig drives the mandatory-PCS verifier.verify: every case needs a PCS
	// System. Exclude cases without one (protocols with committed dynamic-module
	// columns — see the add() closure); they are covered by vanishing.zig's direct
	// path. Filter to a contiguous slice so all downstream indices (system_i,
	// verify_case_i, case_count, the switches) stay aligned.
	var cases []fixtureCase
	var systems []codegen.CompiledSystem
	for i := range allCases {
		if allCases[i].honestPcs == nil {
			continue
		}
		cases = append(cases, allCases[i])
		systems = append(systems, allSystems[i])
	}

	var out bytes.Buffer
	writeVerifyHeader(&out, len(cases))
	opts := codegen.CompiledSystemZigOptions{
		EmitHeader:      false,
		ProtocolImport:  "protocol",
		FieldImport:     "field",
		VanishingImport: "vanishing",
		LogDerivImport:  "logderivativesum",
	}

	for i := range cases {
		if err := codegen.WriteCompiledSystemZig(&out, i, systems[i], opts); err != nil {
			return err
		}
		writeVerifyCase(&out, i, cases[i])
	}
	writeVerifyMetadata(&out, cases, systems)
	writeVerifyCaseSwitch(&out, cases)
	writeVerifyInputSwitch(&out, cases)
	writeVerifyFailingInputSwitch(&out, cases)

	data := out.Bytes()
	zigfmt, err := runZigFmt(data)
	if err == nil {
		data = zigfmt
	}
	return os.WriteFile(filepath.Join("..", "generated", "verify.zig"), data, 0o644)
}

func writeVerifyHeader(out *bytes.Buffer, count int) {
	fmt.Fprintln(out, "// Code generated by verifier-ray/testdata/generate; DO NOT EDIT.")
	fmt.Fprintln(out)
	fmt.Fprintln(out, "const verifier_ray = @import(\"verifier_ray\");")
	fmt.Fprintln(out, "const field = verifier_ray.field.koalabear;")
	fmt.Fprintln(out, "const ext = verifier_ray.field.koalabear_ext;")
	fmt.Fprintln(out, "const protocol = verifier_ray.protocol;")
	fmt.Fprintln(out, "const commitment = verifier_ray.crypto.commitment;")
	fmt.Fprintln(out, "const merkle = verifier_ray.crypto.merkle;")
	fmt.Fprintln(out, "const vanishing = verifier_ray.query.vanishing;")
	fmt.Fprintln(out, "const logderivativesum = verifier_ray.query.logderivativesum;")
	fmt.Fprintln(out, "const pcs = verifier_ray.query.pcs;")
	fmt.Fprintln(out, "const fri = verifier_ray.query.fri;")
	fmt.Fprintln(out, "const verifier = verifier_ray.verifier;")
	fmt.Fprintln(out)
	fmt.Fprintln(out, "pub const VerifyCase = struct {")
	fmt.Fprintln(out, "    name: []const u8,")
	fmt.Fprintln(out, "    spec: protocol.Spec,")
	fmt.Fprintln(out, "    systems: verifier.Systems,")
	fmt.Fprintln(out, "};")
	fmt.Fprintln(out)
	fmt.Fprintln(out, "pub const VerifyCaseMetadata = struct {")
	fmt.Fprintln(out, "    name: []const u8,")
	fmt.Fprintln(out, "    module_count: usize,")
	fmt.Fprintln(out, "    dynamic_module_count: usize,")
	fmt.Fprintln(out, "    round_count: usize,")
	fmt.Fprintln(out, "    expression_count: usize,")
	fmt.Fprintln(out, "    bucket_count: usize,")
	fmt.Fprintln(out, "    vanishing_count: usize,")
	fmt.Fprintln(out, "    total_witness_claims: usize,")
	fmt.Fprintln(out, "    total_quotient_claims: usize,")
	fmt.Fprintln(out, "};")
	fmt.Fprintln(out)
	fmt.Fprintf(out, "pub const case_count: usize = %d;\n", count)
	fmt.Fprintln(out)
}

func writeVerifyCase(out *bytes.Buffer, idx int, tc fixtureCase) {
	// The compile-time PCS system for this case (mandatory). The honest system's
	// batch_roots/maps/zeta are what verifier.Systems.pcs points at; the honest
	// and (optional) failing proofs each carry their own runtime opening.
	pcsName := writePcsSystemZig(out, fmt.Sprintf("verify_case_%d", idx), tc.honestPcs)

	writeVerifyProof(out, fmt.Sprintf("verify_case_%d", idx), tc.honest, tc.honestPcs, tc.honestOpening)
	if tc.invalid != nil {
		writeVerifyProof(out, fmt.Sprintf("verify_case_%d_failing", idx), *tc.invalid, tc.invalidPcs, tc.invalidOpen)
	}
	// The alt (second-size) honest proof, verified against the SAME System's .pcs.
	if tc.alt != nil {
		writeVerifyProof(out, fmt.Sprintf("verify_case_%d_alt", idx), *tc.alt, tc.altPcs, tc.altOpen)
	}
	fmt.Fprintf(
		out,
		"const verify_case_%d_systems = verifier.Systems{ .vanishing = system_%d, .logderivativesum = system_%d_logderiv, .pcs = %s };\n",
		idx, idx, idx, pcsName,
	)
	fmt.Fprintln(out)
}

func writeVerifyProof(out *bytes.Buffer, prefix string, proof vanishingProofView, pcsSys *codegen.PcsSystem, opening fri.OpeningProof) {
	fmt.Fprintf(out, "const %s_module_sizes = [_]usize%s;\n", prefix, intArrayLiteral(proof.moduleSizes))
	fmt.Fprintln(out)

	for roundIdx, round := range proof.rounds {
		writeVerifyRoundData(out, prefix, roundIdx, round)
	}

	fmt.Fprintf(out, "const %s_rounds = [_]protocol.RoundMessage{\n", prefix)
	for roundIdx := range proof.rounds {
		fmt.Fprintf(out, "    .{ .columns = &%s_round_%d_columns, .cells = &%s_round_%d_cells },\n", prefix, roundIdx, prefix, roundIdx)
	}
	fmt.Fprintln(out, "};")
	fmt.Fprintln(out)

	// The PCS opening: the authenticated entry_claims (which vanishing is then
	// re-sliced from) and the FRI opening proof. No witness/quotient_claims —
	// those are derived by the verifier from entry_claims via the claim maps.
	fmt.Fprintf(out, "const %s_pcs_opening = %s;\n", prefix, pcsOpeningZigLiteral(pcsSys, opening))
	fmt.Fprintln(out)

	fmt.Fprintf(out, "const %s_proof = verifier.Proof{\n", prefix)
	fmt.Fprintf(out, "    .rounds = &%s_rounds,\n", prefix)
	fmt.Fprintf(out, "    .module_sizes = &%s_module_sizes,\n", prefix)
	fmt.Fprintf(out, "    .pcs_opening = %s_pcs_opening,\n", prefix)
	fmt.Fprintln(out, "};")
	fmt.Fprintln(out)
}

func writeVerifyRoundData(out *bytes.Buffer, prefix string, roundIdx int, round runtimeTraceRound) {
	for columnIdx, column := range round.columns {
		switch {
		case column.publicBaseValues != nil:
			fmt.Fprintf(out, "const %s_round_%d_column_%d_base = [_]field.Element{\n", prefix, roundIdx, columnIdx)
			for _, value := range column.publicBaseValues {
				fmt.Fprintf(out, "    %s,\n", fieldValueLiteral(value))
			}
			fmt.Fprintln(out, "};")
			fmt.Fprintln(out)
		case column.publicExtValues != nil:
			fmt.Fprintf(out, "const %s_round_%d_column_%d_ext = [_]ext.Ext{\n", prefix, roundIdx, columnIdx)
			for _, value := range column.publicExtValues {
				fmt.Fprintf(out, "    %s,\n", extValueLiteral(value))
			}
			fmt.Fprintln(out, "};")
			fmt.Fprintln(out)
		}
	}

	fmt.Fprintf(out, "const %s_round_%d_columns = [_]protocol.ColumnMessage{\n", prefix, roundIdx)
	for columnIdx, column := range round.columns {
		switch {
		case column.commitments != nil:
			for _, value := range column.commitments {
				fmt.Fprintf(out, "    .{ .oracle_commitment = %s },\n", commitmentValueLiteral(value))
			}
		case column.publicBaseValues != nil:
			fmt.Fprintf(out, "    .{ .public_column = .{ .base = &%s_round_%d_column_%d_base } },\n", prefix, roundIdx, columnIdx)
		case column.publicExtValues != nil:
			fmt.Fprintf(out, "    .{ .public_column = .{ .ext = &%s_round_%d_column_%d_ext } },\n", prefix, roundIdx, columnIdx)
		default:
			panic("runtime trace column has no data variant")
		}
	}
	fmt.Fprintln(out, "};")
	fmt.Fprintln(out)

	fmt.Fprintf(out, "const %s_round_%d_cells = [_]protocol.Scalar{\n", prefix, roundIdx)
	for _, cell := range round.cells {
		switch {
		case cell.baseValue != nil:
			fmt.Fprintf(out, "    .{ .base = %s },\n", fieldValueLiteral(*cell.baseValue))
		case cell.extValue != nil:
			fmt.Fprintf(out, "    .{ .ext = %s },\n", extValueLiteral(*cell.extValue))
		default:
			panic("runtime trace cell has no data variant")
		}
	}
	fmt.Fprintln(out, "};")
	fmt.Fprintln(out)
}

func writeVerifyMetadata(out *bytes.Buffer, cases []fixtureCase, systems []codegen.CompiledSystem) {
	fmt.Fprintln(out, "pub const metadata = [_]VerifyCaseMetadata{")
	for i, tc := range cases {
		vanishingSystem := systems[i].Vanishing
		expressionCount, bucketCount, vanishingCount := vanishingBenchCounts(vanishingSystem)
		fmt.Fprintf(out, "    .{ .name = \"%s\", .module_count = %d, .dynamic_module_count = %d, .round_count = %d, .expression_count = %d, .bucket_count = %d, .vanishing_count = %d, .total_witness_claims = %d, .total_quotient_claims = %d },\n",
			codegen.ZigString(tc.name),
			len(vanishingSystem.Modules),
			vanishingSystem.DynamicModuleCount,
			len(systems[i].Routing.RoundCoinCounts),
			expressionCount,
			bucketCount,
			vanishingCount,
			vanishingSystem.TotalWitnessClaims,
			vanishingSystem.TotalQuotientClaims,
		)
	}
	fmt.Fprintln(out, "};")
	fmt.Fprintln(out)
}

func writeVerifyCaseSwitch(out *bytes.Buffer, cases []fixtureCase) {
	fmt.Fprintln(out, "pub fn get(comptime index: usize) VerifyCase {")
	fmt.Fprintln(out, "    return switch (index) {")
	for i, tc := range cases {
		fmt.Fprintf(
			out,
			"        %d => .{ .name = \"%s\", .spec = system_%d_spec, .systems = verify_case_%d_systems },\n",
			i,
			codegen.ZigString(tc.name),
			i,
			i,
		)
	}
	fmt.Fprintln(out, "        else => @compileError(\"unknown verifier fixture case index\"),")
	fmt.Fprintln(out, "    };")
	fmt.Fprintln(out, "}")
}

// writeVerifyInputSwitch emits the getInput accessor, which returns the proof
// data for a fixture case. The proof is kept separate from VerifyCase (see
// writeVerifyHeader) so callers that only need the spec/systems don't pull in
// the proof, and so the input can be supplied independently at runtime.
func writeVerifyInputSwitch(out *bytes.Buffer, cases []fixtureCase) {
	fmt.Fprintln(out, "pub fn getInput(comptime index: usize) verifier.Proof {")
	fmt.Fprintln(out, "    return switch (index) {")
	for i := range cases {
		fmt.Fprintf(out, "        %d => verify_case_%d_proof,\n", i, i)
	}
	fmt.Fprintln(out, "        else => @compileError(\"unknown verifier fixture case index\"),")
	fmt.Fprintln(out, "    };")
	fmt.Fprintln(out, "}")
}

// writeVerifyFailingInputSwitch emits the getInputFailing accessor, returning
// the failing (invalid) proof data for a fixture case. Not every case defines a
// failing input, so cases without one produce a comptime error when requested.
func writeVerifyFailingInputSwitch(out *bytes.Buffer, cases []fixtureCase) {
	fmt.Fprintln(out, "pub fn getInputFailing(comptime index: usize) verifier.Proof {")
	fmt.Fprintln(out, "    return switch (index) {")
	for i, tc := range cases {
		if tc.invalid != nil {
			fmt.Fprintf(out, "        %d => verify_case_%d_failing_proof,\n", i, i)
		} else {
			fmt.Fprintf(out, "        %d => @compileError(\"verifier fixture case %d (%s) has no failing input\"),\n", i, i, codegen.ZigString(tc.name))
		}
	}
	fmt.Fprintln(out, "        else => @compileError(\"unknown verifier fixture case index\"),")
	fmt.Fprintln(out, "    };")
	fmt.Fprintln(out, "}")
	fmt.Fprintln(out)

	// hasFailing lets a comptime sweep skip getInputFailing for cases that have
	// no failing input (calling it there is a @compileError).
	fmt.Fprintln(out, "pub fn hasFailing(comptime index: usize) bool {")
	fmt.Fprintln(out, "    return switch (index) {")
	for i, tc := range cases {
		fmt.Fprintf(out, "        %d => %t,\n", i, tc.invalid != nil)
	}
	fmt.Fprintln(out, "        else => false,")
	fmt.Fprintln(out, "    };")
	fmt.Fprintln(out, "}")
	fmt.Fprintln(out)

	// getInputAlt returns a case's SECOND-size honest proof (multi-size cases
	// only); hasAlt gates it. The alt proof is verified against the SAME case
	// systems (verify_case_i_systems.pcs) as the primary proof — the
	// runtime-size-reconstructed-layout property: one baked System, two sizes.
	fmt.Fprintln(out, "pub fn getInputAlt(comptime index: usize) verifier.Proof {")
	fmt.Fprintln(out, "    return switch (index) {")
	for i, tc := range cases {
		if tc.alt != nil {
			fmt.Fprintf(out, "        %d => verify_case_%d_alt_proof,\n", i, i)
		} else {
			fmt.Fprintf(out, "        %d => @compileError(\"verifier fixture case %d (%s) has no alt input\"),\n", i, i, codegen.ZigString(tc.name))
		}
	}
	fmt.Fprintln(out, "        else => @compileError(\"unknown verifier fixture case index\"),")
	fmt.Fprintln(out, "    };")
	fmt.Fprintln(out, "}")
	fmt.Fprintln(out)

	fmt.Fprintln(out, "pub fn hasAlt(comptime index: usize) bool {")
	fmt.Fprintln(out, "    return switch (index) {")
	for i, tc := range cases {
		fmt.Fprintf(out, "        %d => %t,\n", i, tc.alt != nil)
	}
	fmt.Fprintln(out, "        else => false,")
	fmt.Fprintln(out, "    };")
	fmt.Fprintln(out, "}")
}

func vanishingBenchCounts(system codegen.VanishingSystem) (expressionCount, bucketCount, vanishingCount int) {
	for _, module := range system.Modules {
		expressionCount += len(module.Expressions)
		bucketCount += len(module.Buckets)
		for _, bucket := range module.Buckets {
			vanishingCount += len(bucket.Vanishings)
		}
	}
	return expressionCount, bucketCount, vanishingCount
}

func fieldValueLiteral(value field.Element) string {
	return fmt.Sprintf(".{ .value = %d }", u(value))
}

func extValueLiteral(value field.Ext) string {
	a0, a1, b0, b1, c0, c1 := field.ExtToUint64s(&value)
	return fmt.Sprintf(
		"ext.Ext{ .B0 = .{ .a0 = .{ .value = %d }, .a1 = .{ .value = %d } }, .B1 = .{ .a0 = .{ .value = %d }, .a1 = .{ .value = %d } }, .B2 = .{ .a0 = .{ .value = %d }, .a1 = .{ .value = %d } } }",
		a0, a1, b0, b1, c0, c1,
	)
}

func commitmentValueLiteral(value field.Octuplet) string {
	parts := make([]string, len(value))
	for i, elem := range value {
		parts[i] = fieldValueLiteral(elem)
	}
	return "commitment.Commitment{ " + strings.Join(parts, ", ") + " }"
}

func intArrayLiteral(values []int) string {
	parts := make([]string, len(values))
	for i, value := range values {
		parts[i] = fmt.Sprintf("%d", value)
	}
	return "{ " + strings.Join(parts, ", ") + " }"
}

func elem(v uint64) field.Element {
	var e field.Element
	e.SetUint64(v)
	return e
}

func elems(values ...uint64) []field.Element {
	out := make([]field.Element, len(values))
	for i, value := range values {
		out[i] = elem(value)
	}
	return out
}

func concreteBase(values []field.Element) *wiop.ConcreteVector {
	return &wiop.ConcreteVector{Plain: field.VecFromBase(values)}
}

func concreteExt(values []field.Ext) *wiop.ConcreteVector {
	return &wiop.ConcreteVector{Plain: field.VecFromExt(values)}
}

func octuplet(values ...uint64) field.Octuplet {
	if len(values) != 8 {
		panic("octuplet requires 8 values")
	}
	var out field.Octuplet
	for i, value := range values {
		out[i] = elem(value)
	}
	return out
}

func commitmentFromElements(values []field.Element) field.Octuplet {
	h := poseidon2.NewMDHasher()
	h.WriteElements(values...)
	return h.SumDigest()
}

func commitmentFromExts(values []field.Ext) field.Octuplet {
	return commitmentFromElements(elementsFromExts(values))
}

func elementsFromExts(values []field.Ext) []field.Element {
	elems := make([]field.Element, 0, len(values)*field.ExtensionDegree)
	for i := range values {
		elems = append(elems,
			values[i].B0.A0,
			values[i].B0.A1,
			values[i].B1.A0,
			values[i].B1.A1,
			values[i].B2.A0,
			values[i].B2.A1,
		)
	}
	return elems
}

func u(e field.Element) uint64 {
	return e.Uint64()
}

func ext6(e field.Ext) string {
	a0, a1, b0, b1, c0, c1 := field.ExtToUint64s(&e)
	return fmt.Sprintf(".{ %d, %d, %d, %d, %d, %d }", a0, a1, b0, b1, c0, c1)
}

func oct8(values field.Octuplet) string {
	parts := make([]string, len(values))
	for i, value := range values {
		parts[i] = fmt.Sprintf("%d", u(value))
	}
	return ".{ " + strings.Join(parts, ", ") + " }"
}

func elemSlice(values []field.Element) string {
	parts := make([]string, len(values))
	for i, value := range values {
		parts[i] = fmt.Sprintf("%d", u(value))
	}
	return ".{ " + strings.Join(parts, ", ") + " }"
}

func extSlice(values []field.Ext) string {
	parts := make([]string, len(values))
	for i, value := range values {
		parts[i] = ext6(value)
	}
	return ".{ " + strings.Join(parts, ", ") + " }"
}

func commitmentSlice(values []field.Octuplet) string {
	parts := make([]string, len(values))
	for i, value := range values {
		parts[i] = oct8(value)
	}
	return ".{ " + strings.Join(parts, ", ") + " }"
}

func bytes4(data [4]byte) string {
	return fmt.Sprintf(".{ 0x%02x, 0x%02x, 0x%02x, 0x%02x }", data[0], data[1], data[2], data[3])
}

func bytes24(data [24]byte) string {
	parts := make([]string, len(data))
	for i, b := range data {
		parts[i] = fmt.Sprintf("0x%02x", b)
	}
	return ".{ " + strings.Join(parts, ", ") + " }"
}

func runZigFmt(data []byte) ([]byte, error) {
	tmp, err := os.CreateTemp("", "verifier-ray-vectors-*.zig")
	if err != nil {
		return nil, err
	}
	defer func() { _ = os.Remove(tmp.Name()) }()
	if _, err := tmp.Write(data); err != nil {
		_ = tmp.Close()
		return nil, err
	}
	if err := tmp.Close(); err != nil {
		return nil, err
	}

	cmd := os.Getenv("ZIG")
	if cmd == "" {
		cmd = "zig"
	}
	if err := exec.Command(cmd, "fmt", tmp.Name()).Run(); err != nil {
		return nil, err
	}
	return os.ReadFile(tmp.Name())
}
