plugins {
  id 'lineth.kotlin-library-conventions'
}

description="Lineth state manager client"

dependencies {
  api project(':jvm-libs:linea:core:domain-models')
  api project(':jvm-libs:linea:core:metrics')
  api project(':jvm-libs:linea:core:client-interface')
  api project(':jvm-libs:generic:json-rpc')
  api project(':jvm-libs:generic:errors')
  api project(':jvm-libs:generic:extensions:futures')
  api project(':jvm-libs:generic:extensions:kotlin')
  api "io.consensys.tuweni:tuweni-bytes:${libs.versions.tuweni.get()}"

  implementation "com.fasterxml.jackson.core:jackson-annotations"
  implementation "com.fasterxml.jackson.core:jackson-databind"
  implementation "com.fasterxml.jackson.module:jackson-module-kotlin"

  testImplementation(project(":jvm-libs:linea:testing:file-system"))
  testImplementation project(':jvm-libs:linea:metrics:micrometer')
  testImplementation "io.vertx:vertx-junit5"
  testImplementation "org.wiremock:wiremock:${libs.versions.wiremock.get()}"
}
