#!/usr/bin/env bats

# Tests for scripts/validate-mdx-partial.sh.
#
# Each test stages an MDX file under a temp repo and runs the script with
# MDX_PARTIAL_PATH pointing at it, then asserts the exit code and stderr/stdout
# via the script's own messages.

setup() {
  REPO="$(mktemp -d)"
  export REPO
  cd "$REPO" || exit 1
  SCRIPT_DIR="$(cd "${BATS_TEST_DIRNAME}/.." && pwd)/scripts"
}

teardown() {
  [[ -n "${REPO:-}" ]] && rm -rf "$REPO"
}

# The validator uses `grep -P` (Perl-compatible regex) for lookbehind/lookahead.
# BSD grep (macOS) does not support -P; skip these tests outside GNU grep.
skip_without_grep_p() {
  if ! printf 'x' | grep -qP 'x' 2>/dev/null; then
    skip "grep -P (GNU grep) not available on this host"
  fi
}

# Helper: write the given content to reference.mdx and run the validator.
run_validator() {
  local content="$1"
  local mdx="$REPO/reference.mdx"
  printf '%s' "$content" > "$mdx"
  MDX_PARTIAL_PATH="$mdx" bash "$SCRIPT_DIR/validate-mdx-partial.sh"
}

@test "accepts a well-formed MDX partial" {
  run run_validator "$(printf '%s\n' \
    '{/* Generated by ./gradlew :coordinator:app:generateConfigDocs. Do not edit by hand. */}' \
    '' \
    '## Section' \
    '' \
    'A value with an escaped brace \{ and an entity &lt;tag&gt;.' \
    '')"
  [ "$status" -eq 0 ]
  [[ "$output" == *"MDX partial OK"* ]]
}

@test "rejects an empty file" {
  : > "$REPO/reference.mdx"
  MDX_PARTIAL_PATH="$REPO/reference.mdx" \
  run bash "$SCRIPT_DIR/validate-mdx-partial.sh"
  [ "$status" -ne 0 ]
  [[ "$output" == *"non-empty MDX partial"* ]]
}

@test "rejects a missing banner" {
  run run_validator "$(printf '%s\n' \
    '## Not a banner' \
    'body')"
  [ "$status" -ne 0 ]
  [[ "$output" == *"missing the generated-content banner"* ]]
}

@test "rejects an unescaped brace in the body" {
  skip_without_grep_p
  run run_validator "$(printf '%s\n' \
    '{/* Generated by ./gradlew :coordinator:app:generateConfigDocs. Do not edit by hand. */}' \
    '' \
    'A raw brace { here.')"
  [ "$status" -ne 0 ]
  [[ "$output" == *"unescaped '{'"* ]]
}

@test "rejects a raw '<' in the body" {
  skip_without_grep_p
  run run_validator "$(printf '%s\n' \
    '{/* Generated by ./gradlew :coordinator:app:generateConfigDocs. Do not edit by hand. */}' \
    '' \
    'A raw <tag> here.')"
  [ "$status" -ne 0 ]
  [[ "$output" == *"raw '<' or '>'"* ]]
}

@test "rejects a leading '>' at the start of the body" {
  skip_without_grep_p
  # Regression: the old [^&]>(?!;) alternative missed a leading '>' because
  # [^&] requires a consuming character before '>'.
  run run_validator "$(printf '%s\n' \
    '{/* Generated by ./gradlew :coordinator:app:generateConfigDocs. Do not edit by hand. */}' \
    '> blockquote start with raw >')"
  [ "$status" -ne 0 ]
  [[ "$output" == *"raw '<' or '>'"* ]]
}

@test "accepts HTML-entity-escaped angle brackets" {
  skip_without_grep_p
  run run_validator "$(printf '%s\n' \
    '{/* Generated by ./gradlew :coordinator:app:generateConfigDocs. Do not edit by hand. */}' \
    '' \
    'Escaped: &lt;tag&gt; and &gt;.')"
  [ "$status" -eq 0 ]
}
