package linea.config.docs

import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test

class ConfigDocMdxGeneratorTest {
  data class SampleFileToml(
    @param:ConfigDoc("The hostname.", example = "localhost")
    val hostname: String,
    @param:ConfigDoc("The port.", default = "5432")
    val port: UInt = 5432u,
    @param:ConfigSection("Nested settings.")
    val nested: NestedToml = NestedToml(),
    @param:ConfigDoc(description = "Legacy gas.", deprecated = true, replacement = "port")
    val legacyGas: ULong? = null,
  ) {
    data class NestedToml(
      @param:ConfigDoc("Max attempts.", default = "3")
      val maxAttempts: UInt = 3u,
    )
  }

  private val detector = sectionByPackagePrefix("linea.config.docs")
  private val files = listOf(ConfigFileRoot("sample", "A sample file.", SampleFileToml::class))

  @Test
  fun `mdx partial opens with an MDX comment banner and drops the top-level heading`() {
    val mdx = ConfigDocMdxGenerator.generate(files, detector, "./gradlew generateDocs")
    assertThat(mdx).startsWith("{/* Generated by ./gradlew generateDocs. Do not edit by hand. */}")
    assertThat(mdx).doesNotContain("# Sample Reference")
    // No H1 line: every '#' must be part of an H2 (## ) or H3 (### ) heading, never a lone "# ".
    assertThat(mdx.lineSequence().none { it.startsWith("# ") }).isTrue()
  }

  @Test
  fun `mdx partial renders file and section headings with backticked section paths`() {
    val mdx = ConfigDocMdxGenerator.generate(files, detector, "./gradlew generateDocs")
    assertThat(mdx).contains("## sample")
    assertThat(mdx).contains("### `nested`")
    assertThat(mdx).contains("| `nested.max-attempts` | `UInt` | no | `3` | active | Max attempts. |")
    assertThat(mdx).contains("The hostname. Example: `localhost`.")
  }

  @Test
  fun `mdx partial escapes braces and angle brackets in prose but not inside inline code`() {
    data class BracesToml(
      @param:ConfigDoc("Use {placeholder} and <tag> carefully.")
      val value: String = "",
    )
    val mdx = ConfigDocMdxGenerator.generate(
      listOf(ConfigFileRoot("braces", "A {file} with <tags>.", BracesToml::class)),
      detector,
      "cmd",
    )
    assertThat(mdx).contains("\\{file\\}")
    assertThat(mdx).contains("&lt;tags&gt;")
    assertThat(mdx).contains("Use \\{placeholder\\} and &lt;tag&gt; carefully.")
  }

  @Test
  fun `mdx partial escapes backticks inside inline code spans`() {
    data class BacktickToml(
      @param:ConfigDoc("A value.", default = "a`b")
      val value: String = "a`b",
    )
    val mdx = ConfigDocMdxGenerator.generate(
      listOf(ConfigFileRoot("bt", "A file.", BacktickToml::class)),
      detector,
      "cmd",
    )
    assertThat(mdx).contains("| `value` | `String` | no | `a&#96;b` | active | A value. |")
  }

  @Test
  fun `mdx partial escapes pipes in table cells`() {
    data class PipeToml(
      @param:ConfigDoc("A|B|C description.")
      val value: String = "",
    )
    val mdx = ConfigDocMdxGenerator.generate(
      listOf(ConfigFileRoot("pipe", "A file.", PipeToml::class)),
      detector,
      "cmd",
    )
    assertThat(mdx).contains("A\\|B\\|C description.")
  }

  @Test
  fun `mdx partial renders a deprecated keys table`() {
    val mdx = ConfigDocMdxGenerator.generate(files, detector, "./gradlew generateDocs")
    assertThat(mdx).contains("## Deprecated Keys")
    assertThat(mdx).contains("| File | Key | Replacement | Description |")
    assertThat(mdx).contains("| sample | `legacy-gas` | `port` | Legacy gas. |")
  }

  @Test
  fun `mdx partial says None when nothing is deprecated`() {
    val mdx = ConfigDocMdxGenerator.generate(
      listOf(ConfigFileRoot("sample", "A file.", SampleFileToml.NestedToml::class)),
      detector,
      "cmd",
    )
    assertThat(mdx).contains("## Deprecated Keys\n\nNone.")
  }

  @Test
  fun `mdx partial does not contain raw JSX-starting tokens that would break MDX imports`() {
    val mdx = ConfigDocMdxGenerator.generate(files, detector, "./gradlew generateDocs")
    // After stripping the leading MDX comment banner, every '{' must be backslash-escaped and
    // every '<'/'>' must be HTML-entity escaped, so the partial is safe to import as MDX.
    val body = mdx.substringAfter("*/}\n")
    val bareBraces = Regex("(?<!\\\\)\\{").findAll(body).count()
    assertThat(bareBraces).isZero()
    assertThat(body).doesNotContain("<").doesNotContain(">")
  }
}
