package linea.config.docs

import org.assertj.core.api.Assertions.assertThat
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.io.TempDir
import java.nio.file.Files
import java.nio.file.Path

class ConfigDocsRunnerTest {
  data class DocumentedToml(
    @param:ConfigDoc("The hostname.", example = "localhost")
    val hostname: String = "localhost",
  )

  data class UndocumentedToml(
    val hostname: String = "localhost",
  )

  private val detector = sectionByPackagePrefix("linea.config.docs")
  private fun files(root: kotlin.reflect.KClass<*>) = listOf(ConfigFileRoot("sample", "A sample file.", root))

  @Test
  fun `runCheck returns 0 and reports OK when fully documented`() {
    val out = StringBuilder()
    val code = ConfigDocsRunner.runCheck(files(DocumentedToml::class), detector, out = out, err = StringBuilder())
    assertThat(code).isEqualTo(0)
    assertThat(out.toString()).contains("all documented")
  }

  @Test
  fun `runCheck returns 1 and reports violations when undocumented`() {
    val err = StringBuilder()
    val code = ConfigDocsRunner.runCheck(files(UndocumentedToml::class), detector, out = StringBuilder(), err = err)
    assertThat(code).isEqualTo(1)
    assertThat(err.toString()).contains("hostname")
  }

  @Test
  fun `generate writes both artifacts and is idempotent`(@TempDir dir: Path) {
    val json = dir.resolve("schema.json")
    val md = dir.resolve("nested/reference.md")
    val logs = mutableListOf<String>()

    ConfigDocsRunner.generate(
      files(DocumentedToml::class),
      detector,
      json,
      md,
      "Sample Reference",
      "./gradlew generate",
    ) { logs.add(it) }

    assertThat(Files.readString(json)).contains("\"sample\"")
    assertThat(Files.readString(md)).contains("# Sample Reference")
    assertThat(logs).allMatch { it.startsWith("Wrote:") }

    // second run: unchanged content => reported as up to date
    val secondLogs = mutableListOf<String>()
    ConfigDocsRunner.generate(
      files(DocumentedToml::class),
      detector,
      json,
      md,
      "Sample Reference",
      "./gradlew generate",
    ) { secondLogs.add(it) }
    assertThat(secondLogs).allMatch { it.startsWith("Up to date:") }
  }

  @Test
  fun `generate writes the MDX partial only when mdxPartialPath is provided`(@TempDir dir: Path) {
    val json = dir.resolve("schema.json")
    val md = dir.resolve("reference.md")
    val mdx = dir.resolve("_generated/sample/reference.mdx")

    ConfigDocsRunner.generate(
      files(DocumentedToml::class),
      detector,
      json,
      md,
      "Sample Reference",
      "./gradlew generate",
      mdxPartialPath = mdx,
    ) { _ -> }

    assertThat(Files.exists(mdx)).isTrue()
    val mdxContent = Files.readString(mdx)
    assertThat(mdxContent).startsWith("{/* Generated by ./gradlew generate. Do not edit by hand. */}")
    assertThat(mdxContent).contains("## sample")
    assertThat(mdxContent).doesNotContain("# Sample Reference")
  }

  @Test
  fun `generate without mdxPartialPath leaves no MDX file behind`(@TempDir dir: Path) {
    val json = dir.resolve("schema.json")
    val md = dir.resolve("reference.md")
    val mdx = dir.resolve("reference.mdx")

    ConfigDocsRunner.generate(
      files(DocumentedToml::class),
      detector,
      json,
      md,
      "Sample Reference",
      "./gradlew generate",
    ) { _ -> }

    assertThat(Files.exists(mdx)).isFalse()
  }

  @Test
  fun `generate preserves committed Markdown and JSON byte-for-byte when MDX is also produced`(
    @TempDir dir: Path,
  ) {
    val json = dir.resolve("schema.json")
    val md = dir.resolve("reference.md")
    val mdx = dir.resolve("_generated/sample/reference.mdx")

    ConfigDocsRunner.generate(
      files(DocumentedToml::class),
      detector,
      json,
      md,
      "Sample Reference",
      "./gradlew generate",
    ) { _ -> }
    val jsonWithoutMdx = Files.readString(json)
    val mdWithoutMdx = Files.readString(md)

    ConfigDocsRunner.generate(
      files(DocumentedToml::class),
      detector,
      json,
      md,
      "Sample Reference",
      "./gradlew generate",
      mdxPartialPath = mdx,
    ) { _ -> }

    assertThat(Files.readString(json)).isEqualTo(jsonWithoutMdx)
    assertThat(Files.readString(md)).isEqualTo(mdWithoutMdx)
    assertThat(Files.exists(mdx)).isTrue()
  }
}
