name: Tracer riscv ACT4 test

on:
  pull_request:
    branches:
      - main
    paths:
      - 'arithmetization/**'
      - '.github/actions/setup-arithmetization-riscv/**'
      - '.github/workflows/arithmetization-*.yml'
  push:
    branches:
     - main
    paths:
     - 'arithmetization/**'
     - '.github/actions/setup-arithmetization-riscv/**'
     - '.github/workflows/arithmetization-*.yml'
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read
  actions: read

jobs:
  act4-reference-tests:
    runs-on: gha-lfdt-lineth-ss-ubuntu-24-amd64-med
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          submodules: false

      - name: Setup Environment
        uses: ./.github/actions/setup-arithmetization-riscv

      - name: Install Sail
        run: make -C arithmetization install-sail

      - name: Build ACT4 ELFs
        run: make act4-build
        working-directory: arithmetization/src/test

      - name: Run ACT4 tests
        run: make act4-exec
        working-directory: arithmetization/src/test
        env:
          ZKC_REF: ${{ inputs.zkc-ref || 'v1.2.22' }}

