name: Tracer riscv-constraints check compilation

on:
  pull_request:
    branches:
      - main
    paths:
      - 'arithmetization/**'
      - '.github/actions/setup-arithmetization-riscv/**'
      - '.github/workflows/arithmetization-*.yml'
  push:
    branches:
     - main
    paths:
     - 'arithmetization/**'
     - '.github/actions/setup-arithmetization-riscv/**'
     - '.github/workflows/arithmetization-*.yml'
  workflow_call:
    inputs:
      zkc-ref:
        description: 'Optional zkc commit/branch/tag (default: arithmetization/Makefile ZKC_REF)'
        required: false
        type: string
  workflow_dispatch:
    inputs:
      zkc-ref:
        description: 'Optional zkc commit/branch/tag (default: arithmetization/Makefile ZKC_REF)'
        required: false
        type: string

permissions:
  contents: read
  actions: read

jobs:
  check-compilation:
    runs-on: gha-lfdt-lineth-ss-ubuntu-24-amd64-small
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          submodules: false

      - name: Setup Environment
        uses: ./.github/actions/setup-arithmetization-riscv
        with:
          zkc-ref: ${{ inputs.zkc-ref }}

      - name: Install zkc and check compilation of RISC-V in ZkC
        run: make -C arithmetization riscv-check-compilation

      - name: Linting Check
        run: make -C arithmetization riscv-check-lint

