name: Tracer simple zkc binary runs and checks

on:
  pull_request:
    branches:
      - main
    paths:
      - 'arithmetization/**'
      - '.github/actions/setup-arithmetization-riscv/**'
      - '.github/workflows/arithmetization-*.yml'
  push:
    branches:
     - main
    paths:
     - 'arithmetization/**'
     - '.github/actions/setup-arithmetization-riscv/**'
     - '.github/workflows/arithmetization-*.yml'
  workflow_call:
    inputs:
      zkc-ref:
        description: 'Optional zkc commit/branch/tag (default: arithmetization/Makefile ZKC_REF)'
        required: false
        type: string
  workflow_dispatch:
    inputs:
      zkc-ref:
        description: 'Optional zkc commit/branch/tag (default: arithmetization/Makefile ZKC_REF)'
        required: false
        type: string

permissions:
  contents: read
  actions: read

jobs:
  binary-run-and-zkc-check:
    runs-on: gha-lfdt-lineth-ss-ubuntu-24-amd64-large
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          submodules: false

      - name: Setup Environment
        uses: ./.github/actions/setup-arithmetization-riscv
        with:
          zkc-ref: ${{ inputs.zkc-ref }}

      - name: Install zkc, compile risc binary for simple zkc test program and check it
        run: make -C arithmetization zkc-compile-and-check
        env:
          ZKC_MAIN: src/test/zkc/simple_add.zkc
          ZKC_FILES: src/test/zkc/simple_add.zkc
          ZKC_INPUT: src/test/zkc/simple_add.json

      - name: Trace Keccak rust and check it
        run: make keccak-rust-exec
        working-directory: arithmetization/src/test
        timeout-minutes: 15
        env:
          ZKC_REF: "" # Empty to avoid installing zkc again
          KECCAK_N_VECTORS: 1
          KECCAK_JSON_FILE: common_inputs/keccak_check.json
          ZKC_EXEC_FLAGS: "--check"